INSERT INTO models (MakeID, modelName) VALUES (24, ' EcoSport')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Everest')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Expedition')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Explorer')
INSERT INTO models (MakeID, modelName) VALUES (24, ' C-MAX')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Fiesta')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Focus')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Fusion')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Mustang')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Ranger')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Escape')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Interceptor')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Indigo')
INSERT INTO models (MakeID, modelName) VALUES (24, ' GT90')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Mustang Giugiaro')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Fairlane')
INSERT INTO models (MakeID, modelName) VALUES (24, ' FX-Atmos')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Evos')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Cirrus')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Atlas')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Airstream')
INSERT INTO models (MakeID, modelName) VALUES (24, ' 021C')
INSERT INTO models (MakeID, modelName) VALUES (24, ' B-Max')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Bronco')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Ikon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Galaxy')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Edge')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Aerostar')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Territory')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Corsair')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Ka')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Model T')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Courier')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Mondeo')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Torino GT')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Torino')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Edsel Ranger')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Figo')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Focus RS')
INSERT INTO models (MakeID, modelName) VALUES (24, ' SVT Focus')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Taurus')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Pinto')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Crown Victoria')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Edsel Villager')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Blush')
INSERT INTO models (MakeID, modelName) VALUES (24, ' S-Max')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Flex')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Kuga')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Bronco II')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Cargo')
INSERT INTO models (MakeID, modelName) VALUES (24, ' F-Series')
INSERT INTO models (MakeID, modelName) VALUES (24, ' E-Series Wagon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Explorer Sport Trac')
INSERT INTO models (MakeID, modelName) VALUES (24, ' LCF')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Super Duty')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Transit')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Transit Connect')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Windstar')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Lightning')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Ranchero')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Country Squire')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Scorpio')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Taurus X')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Tempo')
INSERT INTO models (MakeID, modelName) VALUES (24, ' EXP')
INSERT INTO models (MakeID, modelName) VALUES (24, ' GT40')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Windstar')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Model A')
INSERT INTO models (MakeID, modelName) VALUES (24, ' New Explorer')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Galaxie 500')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Cortina Perana Mk 2')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Granada Perana')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Model C')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Pampa')
INSERT INTO models (MakeID, modelName) VALUES (24, ' 999')
INSERT INTO models (MakeID, modelName) VALUES (24, ' F-Series Super Duty')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Escape Hybrid')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Taurus SHO')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Zephyr')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Probe')
INSERT INTO models (MakeID, modelName) VALUES (24, ' AU Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Prefect')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Mustang Mach 1')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Freestar')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Escort RS Cosworth')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Mustang FR500')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Del Rey')
INSERT INTO models (MakeID, modelName) VALUES (24, ' 7Y')
INSERT INTO models (MakeID, modelName) VALUES (24, ' 1960')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Escort RS 1700T')
INSERT INTO models (MakeID, modelName) VALUES (24, ' John Goss Special')
INSERT INTO models (MakeID, modelName) VALUES (24, ' XY Falcon GT')
INSERT INTO models (MakeID, modelName) VALUES (24, ' CX')
INSERT INTO models (MakeID, modelName) VALUES (24, ' C1 platform')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Mainline')
INSERT INTO models (MakeID, modelName) VALUES (24, ' C-Series')
INSERT INTO models (MakeID, modelName) VALUES (24, ' LTD II')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Focus RS WRC')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Puma')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Crown Victoria Police Interceptor')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Pronto')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Transcontinental')
INSERT INTO models (MakeID, modelName) VALUES (24, ' GTHO Phase III')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Rheinland')
INSERT INTO models (MakeID, modelName) VALUES (24, ' XR Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Del Rio')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Meteor')
INSERT INTO models (MakeID, modelName) VALUES (24, ' 300')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Saphire')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Elite')
INSERT INTO models (MakeID, modelName) VALUES (24, ' XY Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Galaxie 500XL')
INSERT INTO models (MakeID, modelName) VALUES (24, ' XM Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Five Hundred')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Model C Ten')
INSERT INTO models (MakeID, modelName) VALUES (24, ' F-650')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Galaxie')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Tourneo Connect')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Anglia')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Forty-Nine')
INSERT INTO models (MakeID, modelName) VALUES (24, ' XE Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' XA Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' XW Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' BF Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Meteor Rideau')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Fiesta RS Turbo')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Fairlane 500 Skyliner')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Pilot')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Capri Perana')
INSERT INTO models (MakeID, modelName) VALUES (24, ' 7W')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Durango')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Cortina XR6 Interceptor')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Landau')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Cougar')
INSERT INTO models (MakeID, modelName) VALUES (24, ' XK Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Starliner')
INSERT INTO models (MakeID, modelName) VALUES (24, ' LTD')
INSERT INTO models (MakeID, modelName) VALUES (24, ' XL Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Comète')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Fairmont')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Sapphire Cosworth')
INSERT INTO models (MakeID, modelName) VALUES (24, ' LTD Crown Victoria')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Shelby Cobra')
INSERT INTO models (MakeID, modelName) VALUES (24, ' 1932 Model B ')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Escort ZX2')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Ranchero Rio Grande')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Bantam')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Nasim')
INSERT INTO models (MakeID, modelName) VALUES (24, ' California Special Mustang')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Granada')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Fairmont GT')
INSERT INTO models (MakeID, modelName) VALUES (24, ' XP Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' EA Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Torino Talladega')
INSERT INTO models (MakeID, modelName) VALUES (24, ' P68')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Ranch Wagon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Futura')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Model TT')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Parklane')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Vedette')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Shelby Cobra Concept')
INSERT INTO models (MakeID, modelName) VALUES (24, ' GPA')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Corcel')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Classic')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Orion')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Model 91')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Cortina')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Cortina')
INSERT INTO models (MakeID, modelName) VALUES (24, ' FG Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Boss 429')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Boss 302 Mustang')
INSERT INTO models (MakeID, modelName) VALUES (24, ' XF Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' BA Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Eifel')
INSERT INTO models (MakeID, modelName) VALUES (24, ' F-350')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Thames 400E')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Tourneo')
INSERT INTO models (MakeID, modelName) VALUES (24, ' RS200')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Model AA')
INSERT INTO models (MakeID, modelName) VALUES (24, ' XC Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' 1957')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Falcon XR6 Turbo')
INSERT INTO models (MakeID, modelName) VALUES (24, ' 1949 ')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Crestline Skyliner')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Versailles')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Capri')
INSERT INTO models (MakeID, modelName) VALUES (24, ' E83W')
INSERT INTO models (MakeID, modelName) VALUES (24, ' F-250 Super Chief')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Escort Mk1 Perana')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Verona')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Telstar')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Popular')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Model F')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Escort Mk3 Perana')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Escort')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Model K')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Falcon Cobra')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Custom')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Custom 500')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Fairlane Crown Victoria Skyliner')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Thames 300E')
INSERT INTO models (MakeID, modelName) VALUES (24, ' 1955 ')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Sierra RS Cosworth')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Köln')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Contour')
INSERT INTO models (MakeID, modelName) VALUES (24, ' F-550')

INSERT INTO models (MakeID, modelName) VALUES (24, ' Freestyle')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Sierra')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Maverick')
INSERT INTO models (MakeID, modelName) VALUES (24, ' XB Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Thames Trader')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Sierra XR8')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Ranger EV')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Model 48')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Thunderbolt')
INSERT INTO models (MakeID, modelName) VALUES (24, ' EL Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' XT Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Torino Cobra')
INSERT INTO models (MakeID, modelName) VALUES (24, ' 1952 ')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Mustang Cobra Jet')
INSERT INTO models (MakeID, modelName) VALUES (24, ' EB Falcon')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Model Y')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Mustang Boss 351')
INSERT INTO models (MakeID, modelName) VALUES (24, ' 1941 ')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Thunderbird')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Model N')
INSERT INTO models (MakeID, modelName) VALUES (24, ' GT70')
INSERT INTO models (MakeID, modelName) VALUES (24, ' TH!NK')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Royale')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Falcon GT')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Fairlane GT')
INSERT INTO models (MakeID, modelName) VALUES (24, ' 2GA')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Python Automobile')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Mercury Monterey')
INSERT INTO models (MakeID, modelName) VALUES (24, ' SYNus')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Squire')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Maruti Versa')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Thames 307E')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Shelby Mustang')
INSERT INTO models (MakeID, modelName) VALUES (24, ' Country Sedan')
INSERT INTO models (MakeID, modelName) VALUES (24, ' GT')