INSERT INTO models (MakeID, modelName) VALUES (39, ' ELISE')
INSERT INTO models (MakeID, modelName) VALUES (39, ' EXIGE S ROADSTER')
INSERT INTO models (MakeID, modelName) VALUES (39, ' EVORA')
INSERT INTO models (MakeID, modelName) VALUES (39, ' Excel')
INSERT INTO models (MakeID, modelName) VALUES (39, ' Esprit')
INSERT INTO models (MakeID, modelName) VALUES (39, ' Europa')
INSERT INTO models (MakeID, modelName) VALUES (39, ' ELISE CLUB RACER')
INSERT INTO models (MakeID, modelName) VALUES (39, ' ELISE S')
INSERT INTO models (MakeID, modelName) VALUES (39, ' EXIGE S – Roadster M/T')
INSERT INTO models (MakeID, modelName) VALUES (39, ' EVORA S')
INSERT INTO models (MakeID, modelName) VALUES (39, ' EVORA SPORTS RACER')
INSERT INTO models (MakeID, modelName) VALUES (39, ' 77')
INSERT INTO models (MakeID, modelName) VALUES (39, ' 99T')
INSERT INTO models (MakeID, modelName) VALUES (39, ' 72')
INSERT INTO models (MakeID, modelName) VALUES (39, ' E20')
INSERT INTO models (MakeID, modelName) VALUES (39, ' Europa S')
INSERT INTO models (MakeID, modelName) VALUES (39, ' Seven')
INSERT INTO models (MakeID, modelName) VALUES (39, ' Mark VI')
INSERT INTO models (MakeID, modelName) VALUES (39, ' Mk I 1948')
INSERT INTO models (MakeID, modelName) VALUES (39, ' Mk IX')
INSERT INTO models (MakeID, modelName) VALUES (39, ' Eleven')
INSERT INTO models (MakeID, modelName) VALUES (39, ' Elite')
INSERT INTO models (MakeID, modelName) VALUES (39, ' 19')
INSERT INTO models (MakeID, modelName) VALUES (39, ' 2-Eleven')
INSERT INTO models (MakeID, modelName) VALUES (39, ' Exige')
INSERT INTO models (MakeID, modelName) VALUES (39, ' Elan')
INSERT INTO models (MakeID, modelName) VALUES (39, ' 23')
INSERT INTO models (MakeID, modelName) VALUES (39, ' 26R')
INSERT INTO models (MakeID, modelName) VALUES (39, ' Éclat')
INSERT INTO models (MakeID, modelName) VALUES (39, ' Esprit V8')
INSERT INTO models (MakeID, modelName) VALUES (39, ' Elise GT1 Road Car')
INSERT INTO models (MakeID, modelName) VALUES (39, ' Mark IX')
INSERT INTO models (MakeID, modelName) VALUES (39, ' Carlton')
INSERT INTO models (MakeID, modelName) VALUES (39, ' Eclat')
INSERT INTO models (MakeID, modelName) VALUES (39, ' VX220')
