INSERT INTO models (MakeID, modelName) VALUES (52, ' 508')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 5008')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Expert Tepee')
INSERT INTO models (MakeID, modelName) VALUES (52, ' RCZ')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 3008')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 2008')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 308')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 406')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 4007')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 208')
INSERT INTO models (MakeID, modelName) VALUES (52, ' RCZ')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 408')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 107')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Bipper')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 176')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 905')
INSERT INTO models (MakeID, modelName) VALUES (52, ' VLV')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 15')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 907')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 105')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 104')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Talbot Samba')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 125')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 175')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 202')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 36')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 4')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 306')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 5CV')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 56')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 163')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 505')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 305')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 174')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 404')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 5')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Partner')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Pars (also known as Persia)')
INSERT INTO models (MakeID, modelName) VALUES (52, ' P4')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 26')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 3')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 908 HDi FAP')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 33')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 6')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 401')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 608')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Darl’mat')
INSERT INTO models (MakeID, modelName) VALUES (52, ' J5/J7/J9')
INSERT INTO models (MakeID, modelName) VALUES (52, ' iOn')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 601')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 66')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Ludix')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 10')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 4002')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 54')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 106')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Quadrilette')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 405')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 153')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 8')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 604')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 190')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 605')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Hoggar')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Expert')
INSERT INTO models (MakeID, modelName) VALUES (52, ' DMA/DMAH')
INSERT INTO models (MakeID, modelName) VALUES (52, ' D4/D4A')
INSERT INTO models (MakeID, modelName) VALUES (52, ' D3/D3A')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Boxer')
INSERT INTO models (MakeID, modelName) VALUES (52, ' H2Origin')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 304')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 607')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 204')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 302')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 403')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 81')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 205')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 307')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 16')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 1007')
INSERT INTO models (MakeID, modelName) VALUES (52, ' Type 159')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 407')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 207')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 402')
INSERT INTO models (MakeID, modelName) VALUES (52, ' ROA')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 504')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 206')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 309')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 203')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 201')
INSERT INTO models (MakeID, modelName) VALUES (52, ' 301')
