INSERT INTO models (MakeID, modelName) VALUES (58, ' Ghost')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Silver Dawn')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Wraith')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Dawn')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Silver Shadow')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Silver Spirit')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Silver Seraph')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Twenty')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Silver Ghost')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Silver Cloud')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Camargue')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Phantom III')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Phantom VI')
INSERT INTO models (MakeID, modelName) VALUES (58, ' 10 hp')
INSERT INTO models (MakeID, modelName) VALUES (58, ' 15 hp')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Silver Wraith')
INSERT INTO models (MakeID, modelName) VALUES (58, ' 30 hp')
INSERT INTO models (MakeID, modelName) VALUES (58, ' 25/30')
INSERT INTO models (MakeID, modelName) VALUES (58, ' 20/25')
INSERT INTO models (MakeID, modelName) VALUES (58, ' V-8')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Phantom')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Phantom Coupe')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Phantom I')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Phantom II')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Phantom V')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Phantom Drophead Coupé')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Phantom Coupé')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Twenty')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Corniche')
INSERT INTO models (MakeID, modelName) VALUES (58, ' Phantom IV')