INSERT INTO models (MakeID, modelName) VALUES (32, ' Grand Cherokee SRT')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Renegade')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Grand Cherokee Summit Platinum 3.0 CRD')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Wrangler')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Wrangler Unlimited')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Patriot')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Ford Pygmy ')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Renegade')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Willys')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Hurricane')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Trailhawk')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Compass')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Gladiator')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Cherokee')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Liberty')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Commander')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Comanche')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Wrangler YJ (1980)')
INSERT INTO models (MakeID, modelName) VALUES (32, ' DJ')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Wrangler TJ (1990)')
INSERT INTO models (MakeID, modelName) VALUES (32, ' CJ')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Willys-Overland Jeepster')
INSERT INTO models (MakeID, modelName) VALUES (32, ' 2015 Compass Altitude')
INSERT INTO models (MakeID, modelName) VALUES (32, ' 2015 Compass High Altitude')
INSERT INTO models (MakeID, modelName) VALUES (32, ' 2015 Cherokee Model')
INSERT INTO models (MakeID, modelName) VALUES (32, ' 2015 Compass Model')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Grand Cherokee')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Cherokee XJ (1980)')
INSERT INTO models (MakeID, modelName) VALUES (32, ' 2015 Patriot Model')
INSERT INTO models (MakeID, modelName) VALUES (32, ' 2015 Patriot Altitude')
INSERT INTO models (MakeID, modelName) VALUES (32, ' 2015 Wrangler Altitude')
INSERT INTO models (MakeID, modelName) VALUES (32, ' 2015 Wrangler Unlimited Altitude')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Willys MA (1940)')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Honcho (1970)')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Willys MB (1940)')
INSERT INTO models (MakeID, modelName) VALUES (32, ' CJ-7 (1970)')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Wagoneer (1960)')
INSERT INTO models (MakeID, modelName) VALUES (32, ' Forward Control (1960)')
INSERT INTO models (MakeID, modelName) VALUES (32, ' FJ')
