INSERT INTO models (MakeID, modelName) VALUES (33, ' Cadenza')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Optima/Magentis/K5')
INSERT INTO models (MakeID, modelName) VALUES (33, ' K900')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Stinger')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Forte')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Rio')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Sorento')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Niro')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Sportage')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Soul')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Picanto')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Carnival/Sedona')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Seltos SX')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Sportspace')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Telluride')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Ray Hybrid Concept')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Kee')
INSERT INTO models (MakeID, modelName) VALUES (33, ' GT Concept')
INSERT INTO models (MakeID, modelName) VALUES (33, ' KCV III')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Vizen')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Streetrunner')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Slice')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Rondo Taxi')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Rondo SX')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Multi S')
INSERT INTO models (MakeID, modelName) VALUES (33, ' KOUP')
INSERT INTO models (MakeID, modelName) VALUES (33, ' KND-4')
INSERT INTO models (MakeID, modelName) VALUES (33, ' KCV-4 Mojave')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Club')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Alpha')
INSERT INTO models (MakeID, modelName) VALUES (33, ' 18+')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Venga')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Carens/Rondo')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Pop')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Kue')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Potentia')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Cerato')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Avella')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Bongo')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Cee’d')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Credos')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Mohave')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Opirus')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Pride')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Sephia')
INSERT INTO models (MakeID, modelName) VALUES (33, ' KM420')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Rondo')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Borrego')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Cadenza/K7')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Rio/Rio5/Pride')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Rino')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Picanto/Morning')
INSERT INTO models (MakeID, modelName) VALUES (33, ' K9/Quoris')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Forte/Cerato')
INSERT INTO models (MakeID, modelName) VALUES (33, ' K2700/Strong/3000S/2500TCI- KMC only')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Granbird – KMC only')
INSERT INTO models (MakeID, modelName) VALUES (33, ' K4000s – KMC only')
INSERT INTO models (MakeID, modelName) VALUES (33, ' AM928 – KMC only')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Soul Hybrid')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Ray Plug-in hybrid')
INSERT INTO models (MakeID, modelName) VALUES (33, ' cee’d Hybrid')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Spectra')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Brisa')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Spectra')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Combi')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Concord/Capital')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Brisa II/K303')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Pro cee’d')
INSERT INTO models (MakeID, modelName) VALUES (33, ' Mentor')