INSERT INTO models (MakeID, modelName) VALUES (45, ' Panda')
INSERT INTO models (MakeID, modelName) VALUES (45, ' MX7 MarkII')
INSERT INTO models (MakeID, modelName) VALUES (45, ' EC7')
INSERT INTO models (MakeID, modelName) VALUES (45, ' Impreza')
INSERT INTO models (MakeID, modelName) VALUES (45, ' Chairman W')
INSERT INTO models (MakeID, modelName) VALUES (45, ' Actyon')
INSERT INTO models (MakeID, modelName) VALUES (45, ' Rexton II')
INSERT INTO models (MakeID, modelName) VALUES (45, ' Rodius')
INSERT INTO models (MakeID, modelName) VALUES (45, ' Duo Deck Bus')
INSERT INTO models (MakeID, modelName) VALUES (45, ' Priviledge')
INSERT INTO models (MakeID, modelName) VALUES (45, ' MPV')