INSERT INTO models (MakeID, modelName) VALUES (23, ' 500')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Palio Adventure Locker')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 500L')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 500X')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 124 Spider Europa')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Qubo')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Centoventi')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Downtown')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Trepiuno')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Phylla')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Turbina')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Turbina')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Marea')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Tempra')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Stilo')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Sedici')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Oggi')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Fiorino')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Cinquecento')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Bravo')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Albea')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 850')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 515')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Punto')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 512')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Duna')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Panorama')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 522')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Campagnola')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Strada')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Linea')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Uno')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Scudo')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Idea')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Dino')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Croma')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Ritmo')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Regata')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Barchetta')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Siena')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 8V')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Ducato')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Doblò')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Brevetti')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 10 HP')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 16-20 HP')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 132/Argenta')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 502')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Bravo/Brava')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Grande Punto')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Panda')
INSERT INTO models (MakeID, modelName) VALUES (23, ' X1/9')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Autobianchi Y10')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Palio')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Multipla')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 509')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 127')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 242')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Palio Weekend')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 126')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 1500')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 521')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 524')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 518')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 130')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 1800/2100')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 238')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 600')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 510')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 501')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 1300/1500')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 519')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Idea')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Seicento')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 131')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 503')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 147')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Mephistofeles')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Oggi')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 128')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 1400')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Abarth 850TC Berlina')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 2B')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Turbina')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 4 HP')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 507')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Zastava 10')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 124 Coupé')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 505')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 124')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 8 HP')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 124 Sport Spider')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 70')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 60 HP')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 525')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 1100')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Coupé')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Panda Hydrogen')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 500 “Topolino”')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 508')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Eurovans')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 527')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 1200')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 2800')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 520')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 24-32 HP')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 125')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 1')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 2300')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 514')
INSERT INTO models (MakeID, modelName) VALUES (23, ' 6 HP')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Zero')
INSERT INTO models (MakeID, modelName) VALUES (23, ' Elba')
