INSERT INTO models (MakeID, modelName) VALUES (61, ' Sonett III')
INSERT INTO models (MakeID, modelName) VALUES (61, ' 900')
INSERT INTO models (MakeID, modelName) VALUES (61, ' 92')
INSERT INTO models (MakeID, modelName) VALUES (61, ' 95')
INSERT INTO models (MakeID, modelName) VALUES (61, ' 96')
INSERT INTO models (MakeID, modelName) VALUES (61, ' 99')
INSERT INTO models (MakeID, modelName) VALUES (61, ' 9-3')
INSERT INTO models (MakeID, modelName) VALUES (61, ' 9-5')
INSERT INTO models (MakeID, modelName) VALUES (61, ' Aero-X')
INSERT INTO models (MakeID, modelName) VALUES (61, ' 9-2')
INSERT INTO models (MakeID, modelName) VALUES (61, ' 93')
INSERT INTO models (MakeID, modelName) VALUES (61, ' GT750')
INSERT INTO models (MakeID, modelName) VALUES (61, ' Sonett I')
INSERT INTO models (MakeID, modelName) VALUES (61, ' Sonett II')
INSERT INTO models (MakeID, modelName) VALUES (61, ' Sport')
INSERT INTO models (MakeID, modelName) VALUES (61, ' Formula Junior')
INSERT INTO models (MakeID, modelName) VALUES (61, ' 90')
INSERT INTO models (MakeID, modelName) VALUES (61, ' 9000')
INSERT INTO models (MakeID, modelName) VALUES (61, ' 9-2X Linear')
INSERT INTO models (MakeID, modelName) VALUES (61, ' 9-4X')