INSERT INTO models (MakeID, modelName) Values (4 , 'A106' );
INSERT INTO models (MakeID, modelName) Values (4 , 'A110 Berlinette 1300G' );
INSERT INTO models (MakeID, modelName) Values (4 , 'A110 Berlinette Group 4' );
INSERT INTO models (MakeID, modelName) Values (4 , 'A110 Berlinette' );
INSERT INTO models (MakeID, modelName) Values (4 , 'A110' );
INSERT INTO models (MakeID, modelName) Values (4 , 'A210' );
INSERT INTO models (MakeID, modelName) Values (4 , 'A220' );
INSERT INTO models (MakeID, modelName) Values (4 , 'A310 V6 GT Pack' );
INSERT INTO models (MakeID, modelName) Values (4 , 'A441' );
INSERT INTO models (MakeID, modelName) Values (4 , 'A442' );
INSERT INTO models (MakeID, modelName) Values (4 , 'A450' );
INSERT INTO models (MakeID, modelName) Values (4 , 'A460' );
INSERT INTO models (MakeID, modelName) Values (4 , 'A470' );
INSERT INTO models (MakeID, modelName) Values (4 , 'GTA' );
INSERT INTO models (MakeID, modelName) Values (4 , 'M65' );
INSERT INTO models (MakeID, modelName) Values (4 , 'Renault A110 50' );
INSERT INTO models (MakeID, modelName) Values (4 , 'Renault A610 Turbo' );
INSERT INTO models (MakeID, modelName) Values (4 , 'V6 Turbo Le Mans 1990' );
INSERT INTO models (MakeID, modelName) Values (4 , 'Vision' );
INSERT INTO models (MakeID, modelName) Values (4 , 'Willys Interlagos' );