INSERT INTO models (MakeID, modelName) VALUES (16, 'Logan')
INSERT INTO models (MakeID, modelName) VALUES (16, 'Dokker Van')
INSERT INTO models (MakeID, modelName) VALUES (16, 'Sandero Stepway')
INSERT INTO models (MakeID, modelName) VALUES (16, 'Dokker Stepway')
INSERT INTO models (MakeID, modelName) VALUES (16, 'Dokker')
INSERT INTO models (MakeID, modelName) VALUES (16, 'D6')
INSERT INTO models (MakeID, modelName) VALUES (16, 'Duster')
INSERT INTO models (MakeID, modelName) VALUES (16, 'Lastun')
INSERT INTO models (MakeID, modelName) VALUES (16, 'Lodgy')
INSERT INTO models (MakeID, modelName) VALUES (16, 'Lodgy Stepway')
INSERT INTO models (MakeID, modelName) VALUES (16, 'Logan MCV')
INSERT INTO models (MakeID, modelName) VALUES (16, 'Nova')
INSERT INTO models (MakeID, modelName) VALUES (16, 'Gamma')
INSERT INTO models (MakeID, modelName) VALUES (16, 'Sandero')
INSERT INTO models (MakeID, modelName) VALUES (16, 'Solenza')
INSERT INTO models (MakeID, modelName) VALUES (16, 'SupeRNova')
INSERT INTO models (MakeID, modelName) VALUES (16, '1100')
INSERT INTO models (MakeID, modelName) VALUES (16, '1100S')
INSERT INTO models (MakeID, modelName) VALUES (16, '1210')
INSERT INTO models (MakeID, modelName) VALUES (16, '1300')
INSERT INTO models (MakeID, modelName) VALUES (16, '1301')
INSERT INTO models (MakeID, modelName) VALUES (16, '1302')
INSERT INTO models (MakeID, modelName) VALUES (16, '1307')
INSERT INTO models (MakeID, modelName) VALUES (16, '1310')
INSERT INTO models (MakeID, modelName) VALUES (16, '1310 Berlina')
INSERT INTO models (MakeID, modelName) VALUES (16, '1310 Break')
INSERT INTO models (MakeID, modelName) VALUES (16, '1310 P')
INSERT INTO models (MakeID, modelName) VALUES (16, '1320')
INSERT INTO models (MakeID, modelName) VALUES (16, '1325 Liberta')
INSERT INTO models (MakeID, modelName) VALUES (16, '1410')
INSERT INTO models (MakeID, modelName) VALUES (16, '1410 Sport')
INSERT INTO models (MakeID, modelName) VALUES (16, '2000')
INSERT INTO models (MakeID, modelName) VALUES (16, '1325')
