INSERT INTO models (MakeID, modelName) VALUES (19, 'Go+')
INSERT INTO models (MakeID, modelName) VALUES (19, 'on-Do')
INSERT INTO models (MakeID, modelName) VALUES (19, '240Z')
INSERT INTO models (MakeID, modelName) VALUES (19, '720')
INSERT INTO models (MakeID, modelName) VALUES (19, 'Fairlady')
INSERT INTO models (MakeID, modelName) VALUES (19, 'Cherry 100A')
INSERT INTO models (MakeID, modelName) VALUES (19, 'mi-Do')
INSERT INTO models (MakeID, modelName) VALUES (19, 'Sports')
INSERT INTO models (MakeID, modelName) VALUES (19, 'Go')
INSERT INTO models (MakeID, modelName) VALUES (19, 'Roadster')
INSERT INTO models (MakeID, modelName) VALUES (19, 'Z-car')
INSERT INTO models (MakeID, modelName) VALUES (19, 'DC-3')
INSERT INTO models (MakeID, modelName) VALUES (19, 'Truck')
INSERT INTO models (MakeID, modelName) VALUES (19, 'redi-Go')
INSERT INTO models (MakeID, modelName) VALUES (19, 'Prince Homer')
INSERT INTO models (MakeID, modelName) VALUES (19, '200B')
INSERT INTO models (MakeID, modelName) VALUES (19, '1000 DeLuxe')
INSERT INTO models (MakeID, modelName) VALUES (19, '510')
INSERT INTO models (MakeID, modelName) VALUES (19, 'Bluebird 910')
INSERT INTO models (MakeID, modelName) VALUES (19, '1500')
INSERT INTO models (MakeID, modelName) VALUES (19, '1600')
INSERT INTO models (MakeID, modelName) VALUES (19, '2000 Roadster')
INSERT INTO models (MakeID, modelName) VALUES (19, '280ZX')