INSERT INTO models (MakeID, modelName) VALUES (50, ' Astra')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Agila')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Corsa')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Calibra')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Astra G')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Manta')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Admiral')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Olympia')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Meriva')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Zafira')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Omega')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Vectra')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Kadett D')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Astra J')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Meriva B')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Corsa D')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Omega B')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Ascona C')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Tigra')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Insignia')
INSERT INTO models (MakeID, modelName) VALUES (50, ' GT')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Kadett')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Signum')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Movano')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Combo')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Rekord')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Diplomat')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Commodore')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Senator')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Kapitän')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Antara')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Vivaro')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Laubfrosch')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Blitz')
INSERT INTO models (MakeID, modelName) VALUES (50, ' Super 6')