INSERT INTO models (MakeID, modelName) VALUES (57, ' Sabre Four')
INSERT INTO models (MakeID, modelName) VALUES (57, ' TW9')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Scimitar SST 1800 Ti')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Scimitar SS1')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Scimitar Sabre')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Scimitar GTE')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Robin')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Rialto')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Regal')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Rebel')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Kitten Estate')
INSERT INTO models (MakeID, modelName) VALUES (57, ' FW11')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Fox')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Bond Bug')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Rialto Estate')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Rialto')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Rialto Saloon')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Kitten Estate')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Regal')
INSERT INTO models (MakeID, modelName) VALUES (57, ' TW9')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Scimitar GTC')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Rebel saloon')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Kitten')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Scimitar GT')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Regent')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Scimitar SS1')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Sabre Four')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Scimitar GTE')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Scimitar')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Robin')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Kitten saloon')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Scimitar SS1 1800Ti')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Rebel estate')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Scimitar SST 1800 Ti')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Scimitar Sabre')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Bond Bug')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Fox')
INSERT INTO models (MakeID, modelName) VALUES (57, ' Sabre')
INSERT INTO models (MakeID, modelName) VALUES (57, ' FW11')
