INSERT INTO models (MakeID, modelName) VALUES (36, ' Prisma')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Stratos')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Dedra')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Musa')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Dilambda')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Ypsilon')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Thema')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Aurelia')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Sibilo')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Flavia')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Kayak')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Voyager')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Thesis')
INSERT INTO models (MakeID, modelName) VALUES (36, ' FlaLancia')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Appia')
INSERT INTO models (MakeID, modelName) VALUES (36, ' 2000')
INSERT INTO models (MakeID, modelName) VALUES (36, ' 037')
INSERT INTO models (MakeID, modelName) VALUES (36, ' D50A Formula One')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Delta S4 Group B')
INSERT INTO models (MakeID, modelName) VALUES (36, ' LC1 Group 6')
INSERT INTO models (MakeID, modelName) VALUES (36, ' LC2')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Triota')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Beta Torpedo')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Esadelta C')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Esagamma E')
INSERT INTO models (MakeID, modelName) VALUES (36, ' trolleybus in Athens')
INSERT INTO models (MakeID, modelName) VALUES (36, ' 3RO military truck')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Dikappa')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Trevi')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Lambda')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Fulvia Dunja')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Aprilia')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Dialfa-18HP')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Alfa-12HP')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Autobianchi Y10')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Gamma')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Gamma-20HP')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Beta')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Kappa')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Fulvia')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Augusta')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Delta-20/30HP')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Beta-15/20HP')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Theta-35HP')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Trikappa')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Delta')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Montecarlo')
INSERT INTO models (MakeID, modelName) VALUES (36, ' ECV')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Eta-30/50HP')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Delta S4')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Astura')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Artena')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Ardea')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Epsilon')
INSERT INTO models (MakeID, modelName) VALUES (36, ' Lybra')
INSERT INTO models (MakeID, modelName) VALUES (36, ' LC1')
