INSERT INTO models (MakeID, modelName) VALUES (70, ' Stag')
INSERT INTO models (MakeID, modelName) VALUES (70, ' TR6')
INSERT INTO models (MakeID, modelName) VALUES (70, ' TR7')
INSERT INTO models (MakeID, modelName) VALUES (70, ' Dolomite')
INSERT INTO models (MakeID, modelName) VALUES (70, ' Toledo')
INSERT INTO models (MakeID, modelName) VALUES (70, ' TR2')
INSERT INTO models (MakeID, modelName) VALUES (70, ' TR250')
INSERT INTO models (MakeID, modelName) VALUES (70, ' TR3')
INSERT INTO models (MakeID, modelName) VALUES (70, ' TR3A')
INSERT INTO models (MakeID, modelName) VALUES (70, ' TR3B')
INSERT INTO models (MakeID, modelName) VALUES (70, ' TR4')
INSERT INTO models (MakeID, modelName) VALUES (70, ' TR4A')
INSERT INTO models (MakeID, modelName) VALUES (70, ' Roadster')
INSERT INTO models (MakeID, modelName) VALUES (70, ' Acclaim')
INSERT INTO models (MakeID, modelName) VALUES (70, ' GT6')
INSERT INTO models (MakeID, modelName) VALUES (70, ' TR5')
INSERT INTO models (MakeID, modelName) VALUES (70, ' Italia')
INSERT INTO models (MakeID, modelName) VALUES (70, ' Mayflower')
INSERT INTO models (MakeID, modelName) VALUES (70, ' TR8')
INSERT INTO models (MakeID, modelName) VALUES (70, ' Vitesse')
INSERT INTO models (MakeID, modelName) VALUES (70, ' Renown')
INSERT INTO models (MakeID, modelName) VALUES (70, ' 10/20')
INSERT INTO models (MakeID, modelName) VALUES (70, ' TR1')
INSERT INTO models (MakeID, modelName) VALUES (70, ' 1300')
INSERT INTO models (MakeID, modelName) VALUES (70, ' 1500')
INSERT INTO models (MakeID, modelName) VALUES (70, ' 2000')
INSERT INTO models (MakeID, modelName) VALUES (70, ' Herald')
INSERT INTO models (MakeID, modelName) VALUES (70, ' Spitfire')
INSERT INTO models (MakeID, modelName) VALUES (70, ' Super 7')
INSERT INTO models (MakeID, modelName) VALUES (70, ' 15')
INSERT INTO models (MakeID, modelName) VALUES (70, ' 50')
INSERT INTO models (MakeID, modelName) VALUES (70, ' Southern Cross')
INSERT INTO models (MakeID, modelName) VALUES (70, ' 12')
INSERT INTO models (MakeID, modelName) VALUES (70, ' Ten')
INSERT INTO models (MakeID, modelName) VALUES (70, ' Twelve Six')
INSERT INTO models (MakeID, modelName) VALUES (70, ' Super 9')
INSERT INTO models (MakeID, modelName) VALUES (70, ' Continental')
INSERT INTO models (MakeID, modelName) VALUES (70, ' Super 8')
INSERT INTO models (MakeID, modelName) VALUES (70, ' Scorpion')
INSERT INTO models (MakeID, modelName) VALUES (70, ' Gloria')
INSERT INTO models (MakeID, modelName) VALUES (70, ' 13')
INSERT INTO models (MakeID, modelName) VALUES (70, ' 35')
