INSERT INTO models (MakeID, modelName) VALUES (34, ' Quant')
INSERT INTO models (MakeID, modelName) VALUES (34, ' Agera')
INSERT INTO models (MakeID, modelName) VALUES (34, ' CCX')
INSERT INTO models (MakeID, modelName) VALUES (34, ' CC8S')
INSERT INTO models (MakeID, modelName) VALUES (34, ' CCR')
INSERT INTO models (MakeID, modelName) VALUES (34, ' CC')
INSERT INTO models (MakeID, modelName) VALUES (34, ' CCGT')
INSERT INTO models (MakeID, modelName) VALUES (34, ' Regera')
INSERT INTO models (MakeID, modelName) VALUES (34, ' Trevita')
INSERT INTO models (MakeID, modelName) VALUES (34, ' CCX Edition')
INSERT INTO models (MakeID, modelName) VALUES (34, ' CCXR')
INSERT INTO models (MakeID, modelName) VALUES (34, ' Agera S')
INSERT INTO models (MakeID, modelName) VALUES (34, ' CCXR Special Edition')
INSERT INTO models (MakeID, modelName) VALUES (34, ' CCXR Edition')
INSERT INTO models (MakeID, modelName) VALUES (34, ' Agera R')
INSERT INTO models (MakeID, modelName) VALUES (34, ' Agera RS')
INSERT INTO models (MakeID, modelName) VALUES (34, ' Agera Final')
