INSERT INTO models (MakeID, modelName) VALUES (55, ' Catalina')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Chieftain')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Cobalt')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Fiero')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Firebird')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Aztek')
INSERT INTO models (MakeID, modelName) VALUES (55, ' GTO')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Torrents')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Phoenix')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Parisienne')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Ventura')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Custom S')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Executive')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Grand Safari')
INSERT INTO models (MakeID, modelName) VALUES (55, ' G6')
INSERT INTO models (MakeID, modelName) VALUES (55, ' G8')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Le Mans')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Montana minivan')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Parisienne')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Pathfinder')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Safari')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Solstice')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Star Chief 1955')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Streamliner')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Sunbird')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Sunfire')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Tempest')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Trans Sport')
INSERT INTO models (MakeID, modelName) VALUES (55, ' 6000')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Firebird 400')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Safari')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Can Am')
INSERT INTO models (MakeID, modelName) VALUES (55, ' 1000')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Grand Prix')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Firefly')
INSERT INTO models (MakeID, modelName) VALUES (55, ' GTO Judge')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Catalina Super Duty 421')
INSERT INTO models (MakeID, modelName) VALUES (55, ' G3')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Polaris')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Trans Am Super Duty 455')
INSERT INTO models (MakeID, modelName) VALUES (55, ' LeMans')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Vibe')
INSERT INTO models (MakeID, modelName) VALUES (55, ' 2+2')
INSERT INTO models (MakeID, modelName) VALUES (55, ' G5')
INSERT INTO models (MakeID, modelName) VALUES (55, ' Banshee')
			