INSERT INTO models (MakeID, modelName) VALUES (13, 'Pacifica')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Town and Country')
INSERT INTO models (MakeID, modelName) VALUES (13, '300')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Airstream')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Cirrus')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Centura')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Drifter')
INSERT INTO models (MakeID, modelName) VALUES (13, 'LeBaron')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Neon')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Sigma')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Airflow')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Saratoga')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Windsor')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Imperial')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Fifth Avenue')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Cordoba')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Crossfire')
INSERT INTO models (MakeID, modelName) VALUES (13, '150')
INSERT INTO models (MakeID, modelName) VALUES (13, '160 / 180 / 2 Litre')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Model 200')
INSERT INTO models (MakeID, modelName) VALUES (13, '300 letter series')
INSERT INTO models (MakeID, modelName) VALUES (13, '300M')
INSERT INTO models (MakeID, modelName) VALUES (13, '300 non-letter series')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Car Airflow')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Alpine')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Aspen')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Avenger')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Charger')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Concorde')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Colt')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Conquest')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Daytona')
INSERT INTO models (MakeID, modelName) VALUES (13, 'D-50')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Delta')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Dynasty')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Executive')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Horizon')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Galant')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Hunter')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Imperial Parade Phaeton')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Intrepid')
INSERT INTO models (MakeID, modelName) VALUES (13, 'L300 Express')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Lancer')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Laser')
INSERT INTO models (MakeID, modelName) VALUES (13, 'LHS')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Newport')
INSERT INTO models (MakeID, modelName) VALUES (13, 'New Yorker')
INSERT INTO models (MakeID, modelName) VALUES (13, 'New Yorker Fifth Avenue')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Prowler')
INSERT INTO models (MakeID, modelName) VALUES (13, 'PT Cruiser')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Regal')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Plainsman')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Royal')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Sebring')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Stratus')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Sunbeam')
INSERT INTO models (MakeID, modelName) VALUES (13, 'TC')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Touring')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Turbine')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Valiant')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Viper')
INSERT INTO models (MakeID, modelName) VALUES (13, 'VIP')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Vogue')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Voyager/Grand Voyager')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Wayfarer')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Ypsilon')
INSERT INTO models (MakeID, modelName) VALUES (13, '200')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Natrium')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Pronto Cruizer')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Viper GTS-R')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Java')
INSERT INTO models (MakeID, modelName) VALUES (13, 'TEVan')
INSERT INTO models (MakeID, modelName) VALUES (13, '200C EV')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Valiant Charger')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Royal')
INSERT INTO models (MakeID, modelName) VALUES (13, '180')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Atlantic')
INSERT INTO models (MakeID, modelName) VALUES (13, 'TC by Maserati')
INSERT INTO models (MakeID, modelName) VALUES (13, '300C')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Turbine Car')
INSERT INTO models (MakeID, modelName) VALUES (13, 'E-Class')
INSERT INTO models (MakeID, modelName) VALUES (13, 'Nassau')
INSERT INTO models (MakeID, modelName) VALUES (13, '300L')