INSERT INTO models (MakeID, modelName) VALUES (28, ' Q70')
INSERT INTO models (MakeID, modelName) VALUES (28, ' Etherea')
INSERT INTO models (MakeID, modelName) VALUES (28, ' QX60 Hybrid')
INSERT INTO models (MakeID, modelName) VALUES (28, ' J30')
INSERT INTO models (MakeID, modelName) VALUES (28, ' Q45')
INSERT INTO models (MakeID, modelName) VALUES (28, ' Essence')
INSERT INTO models (MakeID, modelName) VALUES (28, ' Emerg e')
INSERT INTO models (MakeID, modelName) VALUES (28, ' QX60')
INSERT INTO models (MakeID, modelName) VALUES (28, ' QX50')
INSERT INTO models (MakeID, modelName) VALUES (28, ' QX70')
INSERT INTO models (MakeID, modelName) VALUES (28, ' Q60')
INSERT INTO models (MakeID, modelName) VALUES (28, ' Q70')
INSERT INTO models (MakeID, modelName) VALUES (28, ' Q40')
INSERT INTO models (MakeID, modelName) VALUES (28, ' QX80')
INSERT INTO models (MakeID, modelName) VALUES (28, ' Q50')
INSERT INTO models (MakeID, modelName) VALUES (28, ' RB10')
INSERT INTO models (MakeID, modelName) VALUES (28, ' Q50 Hybrid')
INSERT INTO models (MakeID, modelName) VALUES (28, ' Q60 Convertible')
INSERT INTO models (MakeID, modelName) VALUES (28, ' Q60 Coupe')
INSERT INTO models (MakeID, modelName) VALUES (28, ' Q60 IPL Convertible')
INSERT INTO models (MakeID, modelName) VALUES (28, ' Q70 Hybrid')
INSERT INTO models (MakeID, modelName) VALUES (28, ' Q70L')
INSERT INTO models (MakeID, modelName) VALUES (28, ' M45')
INSERT INTO models (MakeID, modelName) VALUES (28, ' G20')
INSERT INTO models (MakeID, modelName) VALUES (28, ' G37')
INSERT INTO models (MakeID, modelName) VALUES (28, ' I35')
INSERT INTO models (MakeID, modelName) VALUES (28, ' M35')
INSERT INTO models (MakeID, modelName) VALUES (28, ' JX35')
INSERT INTO models (MakeID, modelName) VALUES (28, ' M30')
INSERT INTO models (MakeID, modelName) VALUES (28, ' M56')
INSERT INTO models (MakeID, modelName) VALUES (28, ' I30')
INSERT INTO models (MakeID, modelName) VALUES (28, ' G25')
INSERT INTO models (MakeID, modelName) VALUES (28, ' QX4')
INSERT INTO models (MakeID, modelName) VALUES (28, ' Kuraza')
INSERT INTO models (MakeID, modelName) VALUES (28, ' IPL Q50')