INSERT INTO models (MakeID, modelName) VALUES (35, ' Aventador')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Diablo')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Veneno')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Centenario')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Huracan')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Sesto Elemento')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Urus')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Murcielago')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Jarama')
INSERT INTO models (MakeID, modelName) VALUES (35, ' 400GT')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Miura')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Gallardo Super Trofeo')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Gallardo Superleggera')
INSERT INTO models (MakeID, modelName) VALUES (35, ' LM')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Veneno Car Zero')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Islero')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Diablo GT')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Urraco')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Aventador Roadster')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Bicolore Gallardo')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Countach LP400')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Espada 1968')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Alar')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Silhouette')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Jalpa')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Estoque')
INSERT INTO models (MakeID, modelName) VALUES (35, ' 350GT')
INSERT INTO models (MakeID, modelName) VALUES (35, ' Reventón')
INSERT INTO models (MakeID, modelName) VALUES (35, ' LM002')