INSERT INTO models (MakeID, modelName) VALUES (29, ' Crosswind')
INSERT INTO models (MakeID, modelName) VALUES (29, ' D-Max')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Mu-X')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Panther')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Faster')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Bellel')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Ascender')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Florian')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Trooper')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Axiom')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Stylus')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Oasis')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Aska')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Amigo')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Elf')
INSERT INTO models (MakeID, modelName) VALUES (29, ' i 350')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Gala Mio')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Hombre')
INSERT INTO models (MakeID, modelName) VALUES (29, ' i 290')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Pickup')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Turquoise')
INSERT INTO models (MakeID, modelName) VALUES (29, ' i 280')
INSERT INTO models (MakeID, modelName) VALUES (29, ' E-Series')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Forward')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Giga')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Piazza')
INSERT INTO models (MakeID, modelName) VALUES (29, ' F-Series')
INSERT INTO models (MakeID, modelName) VALUES (29, ' i-Series')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Rodeo')
INSERT INTO models (MakeID, modelName) VALUES (29, ' VehiCROSS')
INSERT INTO models (MakeID, modelName) VALUES (29, ' i-Van')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Bellett')
INSERT INTO models (MakeID, modelName) VALUES (29, ' C-Series')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Geo Storm')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Wizard')
INSERT INTO models (MakeID, modelName) VALUES (29, ' 117 Coupé')
INSERT INTO models (MakeID, modelName) VALUES (29, ' Amigo')
INSERT INTO models (MakeID, modelName) VALUES (29, ' TF')
INSERT INTO models (MakeID, modelName) VALUES (29, ' N-Series')
INSERT INTO models (MakeID, modelName) VALUES (29, ' GeI')