INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'ATS Coupe' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Allanté' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'BLS' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'CT6' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'CTS' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'CTS-V' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Calais' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Cimarron' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Coupe de Ville' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'DTS' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Eldorado' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Escalade' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Model D' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Model Thirty' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Northstar LMP' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'SRX' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'STS' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'STS-V' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Series 314' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Series 341' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Series 60' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Series 61' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Series 62' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Series 65' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Series 70' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Seville' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Sixty Special' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Type 51' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Type 53' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Type 57' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Type 59' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Type 61' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'Type V-63' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'V-16' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'XLR' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'XLR-V' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'XT5' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'XTS' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'de Ville series' );
INSERT INTO models (MakeID, modelName) VALUES ( 11 ,'de Ville' );