INSERT INTO models (MakeID, modelName) VALUES (27, ' Santa Fe')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Tucson')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Accent')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Creta')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Grandeur')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Eon')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Elantra')
INSERT INTO models (MakeID, modelName) VALUES (27, ' i10')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Blue-Will')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Clix')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Intrado')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Genesis Coupe')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Vision G')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Terracan')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Nuvis')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Grand i10')
INSERT INTO models (MakeID, modelName) VALUES (27, ' i20')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Mistra')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Veracruz')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Sonata')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Trajet')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Galloper')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Atos')
INSERT INTO models (MakeID, modelName) VALUES (27, ' BlueOn')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Excel')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Equus')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Lavita')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Getz')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Tiburon')
INSERT INTO models (MakeID, modelName) VALUES (27, ' HB20')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Dynasty')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Libero')
INSERT INTO models (MakeID, modelName) VALUES (27, ' New Tucson')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Pony')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Grand Santa Fe')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Genesis (2008–present)')
INSERT INTO models (MakeID, modelName) VALUES (27, ' i20 Cross Sport')
INSERT INTO models (MakeID, modelName) VALUES (27, ' i20 WRC')
INSERT INTO models (MakeID, modelName) VALUES (27, ' i30')
INSERT INTO models (MakeID, modelName) VALUES (27, ' i40')
INSERT INTO models (MakeID, modelName) VALUES (27, ' ix20')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Veloster Turbo')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Porter')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Starex')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Grand Starex')
INSERT INTO models (MakeID, modelName) VALUES (27, ' 4.5 to 5-ton truck')
INSERT INTO models (MakeID, modelName) VALUES (27, ' 8 to 25-ton truck')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Santamo')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Aero')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Sonata Embera')
INSERT INTO models (MakeID, modelName) VALUES (27, ' e-Mighty')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Mighty II')
INSERT INTO models (MakeID, modelName) VALUES (27, ' HED-5')
INSERT INTO models (MakeID, modelName) VALUES (27, ' New Power Truck')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Global 900')
INSERT INTO models (MakeID, modelName) VALUES (27, ' County')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Universe')
INSERT INTO models (MakeID, modelName) VALUES (27, ' H-100')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Super Truck Medium')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Entourage')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Super Truck')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Mega Truck')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Chorus')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Trago')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Grace')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Verna')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Aero Town')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Aero City')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Mighty')
INSERT INTO models (MakeID, modelName) VALUES (27, ' Marcia')