INSERT INTO models (MakeID, modelName) VALUES (42, ' 3')
INSERT INTO models (MakeID, modelName) VALUES (42, ' 2')
INSERT INTO models (MakeID, modelName) VALUES (42, ' 6')
INSERT INTO models (MakeID, modelName) VALUES (42, ' CX-5')
INSERT INTO models (MakeID, modelName) VALUES (42, ' CX-9')
INSERT INTO models (MakeID, modelName) VALUES (42, ' CX-7')
INSERT INTO models (MakeID, modelName) VALUES (42, ' 5')
INSERT INTO models (MakeID, modelName) VALUES (42, ' MX-5')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Laputa')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Savanna')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Carol')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Millenia')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Xedos 6')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Tribute')
INSERT INTO models (MakeID, modelName) VALUES (42, ' CX-3')
INSERT INTO models (MakeID, modelName) VALUES (42, ' BT-50')
INSERT INTO models (MakeID, modelName) VALUES (42, ' RX-3')
INSERT INTO models (MakeID, modelName) VALUES (42, ' RX-8')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Atenza')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Axela')
INSERT INTO models (MakeID, modelName) VALUES (42, ' MX-5 RF')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Nagare')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Kiyora')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Ryuga')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Sassou')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Senku')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Taiki')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Hakaze')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Kabura')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Furai')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Kazamai')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Takeri')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Shinari')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Minagi')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Kaan')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Activehicle')
INSERT INTO models (MakeID, modelName) VALUES (42, ' MX-5 Superlight')
INSERT INTO models (MakeID, modelName) VALUES (42, ' MX-04')
INSERT INTO models (MakeID, modelName) VALUES (42, ' MX-03')
INSERT INTO models (MakeID, modelName) VALUES (42, ' MX-02')
INSERT INTO models (MakeID, modelName) VALUES (42, ' MV-X')
INSERT INTO models (MakeID, modelName) VALUES (42, ' MS-X')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Miata Mono-Posto')
INSERT INTO models (MakeID, modelName) VALUES (42, ' London Taxi')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Le Mans Prototype')
INSERT INTO models (MakeID, modelName) VALUES (42, ' HR-X 2')
INSERT INTO models (MakeID, modelName) VALUES (42, ' HR-X')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Gissya')
INSERT INTO models (MakeID, modelName) VALUES (42, ' CVS ')
INSERT INTO models (MakeID, modelName) VALUES (42, ' CU-X')
INSERT INTO models (MakeID, modelName) VALUES (42, ' BU-X')
INSERT INTO models (MakeID, modelName) VALUES (42, ' AZ550')
INSERT INTO models (MakeID, modelName) VALUES (42, ' MX-81')
INSERT INTO models (MakeID, modelName) VALUES (42, ' TD-R')
INSERT INTO models (MakeID, modelName) VALUES (42, ' SW-X')
INSERT INTO models (MakeID, modelName) VALUES (42, ' SU-V')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Secret Hideout')
INSERT INTO models (MakeID, modelName) VALUES (42, ' RX-Evolv')
INSERT INTO models (MakeID, modelName) VALUES (42, ' RX-500')
INSERT INTO models (MakeID, modelName) VALUES (42, ' RX-01')
INSERT INTO models (MakeID, modelName) VALUES (42, ' RX 87')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Nextourer')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Neospace')
INSERT INTO models (MakeID, modelName) VALUES (42, ' MX-Micro Sport')
INSERT INTO models (MakeID, modelName) VALUES (42, ' MX-Flexa')
INSERT INTO models (MakeID, modelName) VALUES (42, ' MX-Crossport')
INSERT INTO models (MakeID, modelName) VALUES (42, ' MX Sportif ')
INSERT INTO models (MakeID, modelName) VALUES (42, ' MX Sport Tourier')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Ford Courier')
INSERT INTO models (MakeID, modelName) VALUES (42, ' RX-2')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Navajo')
INSERT INTO models (MakeID, modelName) VALUES (42, ' R360')
INSERT INTO models (MakeID, modelName) VALUES (42, ' R100')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Familia Astina')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Roadpacer AP')
INSERT INTO models (MakeID, modelName) VALUES (42, ' MXR-01')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Cronos')
INSERT INTO models (MakeID, modelName) VALUES (42, 'speed3')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Sentia')
INSERT INTO models (MakeID, modelName) VALUES (42, ' 737C')
INSERT INTO models (MakeID, modelName) VALUES (42, ' 717C')
INSERT INTO models (MakeID, modelName) VALUES (42, ' 121')
INSERT INTO models (MakeID, modelName) VALUES (42, ' 323F')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Ford Laser')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Efini MS-8')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Autozam Revue')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Ford Festiva')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Rotary Pickup')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Sao Penza')
INSERT INTO models (MakeID, modelName) VALUES (42, ' AZ-Wagon')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Biante')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Titan')
INSERT INTO models (MakeID, modelName) VALUES (42, ' go')
INSERT INTO models (MakeID, modelName) VALUES (42, ' 787B')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Premacy')
INSERT INTO models (MakeID, modelName) VALUES (42, ' 757')
INSERT INTO models (MakeID, modelName) VALUES (42, ' 727C')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Demio')
INSERT INTO models (MakeID, modelName) VALUES (42, ' RX-8 Hydrogen RE')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Premacy Hydrogen RE Hybrid')
INSERT INTO models (MakeID, modelName) VALUES (42, ' AZ-Offroad')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Familia')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Persona')
INSERT INTO models (MakeID, modelName) VALUES (42, ' 929')
INSERT INTO models (MakeID, modelName) VALUES (42, ' 3')
INSERT INTO models (MakeID, modelName) VALUES (42, ' MPV')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Nasim')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Bongo')
INSERT INTO models (MakeID, modelName) VALUES (42, ' RX-792P')
INSERT INTO models (MakeID, modelName) VALUES (42, ' MX-5 10th Anniversary Model')
INSERT INTO models (MakeID, modelName) VALUES (42, ' RX-7')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Capella')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Verisa')
INSERT INTO models (MakeID, modelName) VALUES (42, ' MX-3')
INSERT INTO models (MakeID, modelName) VALUES (42, ' B-Series')
INSERT INTO models (MakeID, modelName) VALUES (42, ' RX-4')
INSERT INTO models (MakeID, modelName) VALUES (42, ' 6')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Porter')
INSERT INTO models (MakeID, modelName) VALUES (42, ' MX-6')
INSERT INTO models (MakeID, modelName) VALUES (42, ' Mercury Tracer')