INSERT INTO models (MakeID, modelName) Values (7 , '3-Litre' );
INSERT INTO models (MakeID, modelName) Values (7 , '8 Litre 4-door sports saloon' );
INSERT INTO models (MakeID, modelName) Values (7 , '8-Litre' );
INSERT INTO models (MakeID, modelName) Values (7 , 'Arnage T' );
INSERT INTO models (MakeID, modelName) Values (7 , 'Arnage' );
INSERT INTO models (MakeID, modelName) Values (7 , 'Azure Mulliner' );
INSERT INTO models (MakeID, modelName) Values (7 , 'Azure' );
INSERT INTO models (MakeID, modelName) Values (7 , 'Bentayga Hybrid' );
INSERT INTO models (MakeID, modelName) Values (7 , 'Bentayga SUV' );
INSERT INTO models (MakeID, modelName) Values (7 , 'Blower' );
INSERT INTO models (MakeID, modelName) Values (7 , 'Blower' );
INSERT INTO models (MakeID, modelName) Values (7 , 'Blue Train' );
INSERT INTO models (MakeID, modelName) Values (7 , 'Brooklands' );
INSERT INTO models (MakeID, modelName) Values (7 , 'Continental Flying Spur' );
INSERT INTO models (MakeID, modelName) Values (7 , 'Continental GT (II)' );
INSERT INTO models (MakeID, modelName) Values (7 , 'Continental GT' );
INSERT INTO models (MakeID, modelName) Values (7 , 'Continental Supersports' );
INSERT INTO models (MakeID, modelName) Values (7 , 'Continental' );
INSERT INTO models (MakeID, modelName) Values (7 , 'Mark VI' );
INSERT INTO models (MakeID, modelName) Values (7 , 'Mulsanne Turbo' );
INSERT INTO models (MakeID, modelName) Values (7 , 'Mulsanne' );
INSERT INTO models (MakeID, modelName) Values (7 , 'R-Type Continental' );
INSERT INTO models (MakeID, modelName) Values (7 , 'S series Standard Saloon' );
INSERT INTO models (MakeID, modelName) Values (7 , 'Speed Six' );
INSERT INTO models (MakeID, modelName) Values (7 , 'T series Standard Saloon' );