INSERT INTO models (MakeID, modelName) VALUES (65, ' Forfour')
INSERT INTO models (MakeID, modelName) VALUES (65, ' BRABUS Forfour')
INSERT INTO models (MakeID, modelName) VALUES (65, ' BRABUS Fortwo')
INSERT INTO models (MakeID, modelName) VALUES (65, ' BRABUS Fortwo Cabrio')
INSERT INTO models (MakeID, modelName) VALUES (65, ' Cabrio Tailor Made')
INSERT INTO models (MakeID, modelName) VALUES (65, ' EQ Forfour')
INSERT INTO models (MakeID, modelName) VALUES (65, ' EQ Fortwo')
INSERT INTO models (MakeID, modelName) VALUES (65, ' EQ Fortwo Cabrio')
INSERT INTO models (MakeID, modelName) VALUES (65, ' Fortwo')
INSERT INTO models (MakeID, modelName) VALUES (65, ' Fortwo Cabrio')
INSERT INTO models (MakeID, modelName) VALUES (65, ' Fortwo Special Models')
INSERT INTO models (MakeID, modelName) VALUES (65, ' Crossblade')
INSERT INTO models (MakeID, modelName) VALUES (65, ' Edition #1')
INSERT INTO models (MakeID, modelName) VALUES (65, ' Formore')
INSERT INTO models (MakeID, modelName) VALUES (65, ' Fortwo Electric Drive')
INSERT INTO models (MakeID, modelName) VALUES (65, ' Roadster')
INSERT INTO models (MakeID, modelName) VALUES (65, ' Fortwo Electric Drive')
INSERT INTO models (MakeID, modelName) VALUES (65, ' K')
INSERT INTO models (MakeID, modelName) VALUES (65, ' City Coupe and City Cabrio')
INSERT INTO models (MakeID, modelName) VALUES (65, ' Fortwo Cabriolet')
INSERT INTO models (MakeID, modelName) VALUES (65, ' Fortwo ED')