INSERT INTO models (MakeID, modelName) VALUES (17, 'Tacuma')
INSERT INTO models (MakeID, modelName) VALUES (17, 'Matiz')
INSERT INTO models (MakeID, modelName) VALUES (17, 'Leganza')
INSERT INTO models (MakeID, modelName) VALUES (17, 'Lanos')
INSERT INTO models (MakeID, modelName) VALUES (17, 'Tosca')
INSERT INTO models (MakeID, modelName) VALUES (17, 'Tico')
INSERT INTO models (MakeID, modelName) VALUES (17, 'Rezzo')
INSERT INTO models (MakeID, modelName) VALUES (17, 'Magnus')
INSERT INTO models (MakeID, modelName) VALUES (17, 'Nubira')
INSERT INTO models (MakeID, modelName) VALUES (17, 'Lacetti')
INSERT INTO models (MakeID, modelName) VALUES (17, 'Gentra')
INSERT INTO models (MakeID, modelName) VALUES (17, 'Espero')
INSERT INTO models (MakeID, modelName) VALUES (17, 'BH120')
INSERT INTO models (MakeID, modelName) VALUES (17, 'Damas')
INSERT INTO models (MakeID, modelName) VALUES (17, 'Labo')
INSERT INTO models (MakeID, modelName) VALUES (17, 'Honker')
INSERT INTO models (MakeID, modelName) VALUES (17, 'LeMans')
INSERT INTO models (MakeID, modelName) VALUES (17, 'Veritas')
INSERT INTO models (MakeID, modelName) VALUES (17, 'Winstorm')
INSERT INTO models (MakeID, modelName) VALUES (17, 'Tarpan Honker')
INSERT INTO models (MakeID, modelName) VALUES (17, 'Maruti Versa')