INSERT INTO models (MakeID, modelName) Values (6 , '100' );
INSERT INTO models (MakeID, modelName) Values (6 , '200' );
INSERT INTO models (MakeID, modelName) Values (6 , '4000CS Quattro' );
INSERT INTO models (MakeID, modelName) Values (6 , '4000CS' );
INSERT INTO models (MakeID, modelName) Values (6 , '4000s Quattro' );
INSERT INTO models (MakeID, modelName) Values (6 , '4000s' );
INSERT INTO models (MakeID, modelName) Values (6 , '50 (86)' );
INSERT INTO models (MakeID, modelName) Values (6 , '5000' );
INSERT INTO models (MakeID, modelName) Values (6 , '5000CS Quattro' );
INSERT INTO models (MakeID, modelName) Values (6 , '5000CS' );
INSERT INTO models (MakeID, modelName) Values (6 , '5000S' );
INSERT INTO models (MakeID, modelName) Values (6 , '80');
INSERT INTO models (MakeID, modelName) Values (6 , '80/90' );
INSERT INTO models (MakeID, modelName) Values (6 , '90' );
INSERT INTO models (MakeID, modelName) Values (6 , '90' );
INSERT INTO models (MakeID, modelName) Values (6 , 'A1' );
INSERT INTO models (MakeID, modelName) Values (6 , 'A2' );
INSERT INTO models (MakeID, modelName) Values (6 , 'A2' );
INSERT INTO models (MakeID, modelName) Values (6 , 'A3' );
INSERT INTO models (MakeID, modelName) Values (6 , 'A4' );
INSERT INTO models (MakeID, modelName) Values (6 , 'A5' );
INSERT INTO models (MakeID, modelName) Values (6 , 'A6' );
INSERT INTO models (MakeID, modelName) Values (6 , 'A7 Sportback' );
INSERT INTO models (MakeID, modelName) Values (6 , 'A7' );
INSERT INTO models (MakeID, modelName) Values (6 , 'A8 L' );
INSERT INTO models (MakeID, modelName) Values (6 , 'A8' );
INSERT INTO models (MakeID, modelName) Values (6 , 'AI Trail Quattro' );
INSERT INTO models (MakeID, modelName) Values (6 , 'AI me' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Aicon' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Allroad' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Avantissimo' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Avus Quattro' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Avus quattro' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Cabriolet' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Coupe GT' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Coupe Quattro' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Coupé B2 (81/85)' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Coupé' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Elaine' );
INSERT INTO models (MakeID, modelName) Values (6 , 'F103' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Le Mans quattro' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Lemans Quattro' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Nanuk Quattro' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Nuvolari Quattro' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Nuvolari quattro' );
INSERT INTO models (MakeID, modelName) Values (6 , 'PB18 e-tron' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Pikes Peak quattro' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Pop.Up Next' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Prologue Allroad' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Prologue' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Q3' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Q4 e-tron' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Q5' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Q7' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Quartz' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Quattro B2 (85)' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Quattro Spyder' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Quattro' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Quattro' );
INSERT INTO models (MakeID, modelName) Values (6 , 'R10 TDI' );
INSERT INTO models (MakeID, modelName) Values (6 , 'R15 TDI' );
INSERT INTO models (MakeID, modelName) Values (6 , 'R8 Coupe' );
INSERT INTO models (MakeID, modelName) Values (6 , 'R8 Spyder' );
INSERT INTO models (MakeID, modelName) Values (6 , 'R8C' );
INSERT INTO models (MakeID, modelName) Values (6 , 'R8R' );
INSERT INTO models (MakeID, modelName) Values (6 , 'RS 2 Avant' );
INSERT INTO models (MakeID, modelName) Values (6 , 'RS 4' );
INSERT INTO models (MakeID, modelName) Values (6 , 'RS 6 quattro' );
INSERT INTO models (MakeID, modelName) Values (6 , 'RS2 Avant (8C)' );
INSERT INTO models (MakeID, modelName) Values (6 , 'RS4 quattro' );
INSERT INTO models (MakeID, modelName) Values (6 , 'RS4' );
INSERT INTO models (MakeID, modelName) Values (6 , 'RS5' );
INSERT INTO models (MakeID, modelName) Values (6 , 'RS6' );
INSERT INTO models (MakeID, modelName) Values (6 , 'RSQ' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Roadjet' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Rosemeyer' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Rosemeyer' );
INSERT INTO models (MakeID, modelName) Values (6 , 'S2' );
INSERT INTO models (MakeID, modelName) Values (6 , 'S3' );
INSERT INTO models (MakeID, modelName) Values (6 , 'S4' );
INSERT INTO models (MakeID, modelName) Values (6 , 'S5 (B8/8T)' );
INSERT INTO models (MakeID, modelName) Values (6 , 'S6' );
INSERT INTO models (MakeID, modelName) Values (6 , 'S8' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Shooting Brake' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Space Frame' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Sportback concept' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Steppenwolf' );
INSERT INTO models (MakeID, modelName) Values (6 , 'TT Car Model' );
INSERT INTO models (MakeID, modelName) Values (6 , 'Ur-S4 / Ur-S6' );
INSERT INTO models (MakeID, modelName) Values (6 , 'V8 (4C)' );
INSERT INTO models (MakeID, modelName) Values (6 , 'e-tron GT' );
INSERT INTO models (MakeID, modelName) Values (6 , 'e-tron' );