INSERT INTO models (MakeID, modelName) VALUES (69, ' Camry')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Corolla Altis')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Vios')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Wigo')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Yaris')
INSERT INTO models (MakeID, modelName) VALUES (69, ' FJ Cruiser')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Fortuner')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Rush')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Prado')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Rav4')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Land Cruiser')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Avanza')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Avanza Veloz')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Innova')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Wish')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Alphard')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Previa')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Hiace')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Hilux')
INSERT INTO models (MakeID, modelName) VALUES (69, ' FT-86 G Sports Concept')
INSERT INTO models (MakeID, modelName) VALUES (69, ' FT-CH Concept')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Prius C concept')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Sports EV Twin')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Yaris HSD Concept')
INSERT INTO models (MakeID, modelName) VALUES (69, ' FT-1')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Sequoia')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Avensis')
INSERT INTO models (MakeID, modelName) VALUES (69, ' bB')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Comfort')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Porte')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Sienna')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Noah')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Ipsum')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Tacoma')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Prius')
INSERT INTO models (MakeID, modelName) VALUES (69, ' 86')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Aygo')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Brevis')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Aurion')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Allion')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Etios')
INSERT INTO models (MakeID, modelName) VALUES (69, ' ist')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Mark X')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Avalon')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Crown')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Belta')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Auris')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Vitz')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Matrix')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Century')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Highlander')
INSERT INTO models (MakeID, modelName) VALUES (69, ' iQ')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Premio')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Vios Exclusive')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Land Cruiser 200')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Venza')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Tundra')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Condor')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Isis')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Ractis')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Raum')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Sienta')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Verso')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Calya (also called Daihatsu Sigra)')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Coaster')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Prius C')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Sai')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Sera ')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Paseo ')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Tercel ')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Starlet ')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Celica')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Supra')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Prius Plug-in Hybrid')
INSERT INTO models (MakeID, modelName) VALUES (69, ' RSC')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Celica XX')
INSERT INTO models (MakeID, modelName) VALUES (69, ' QuickDelivery')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Hilux Surf')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Probox')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Origin')
INSERT INTO models (MakeID, modelName) VALUES (69, ' TS010')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Stout')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Starlet Glanza')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Succeed')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Carina ED')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Crown Comfort LPG')
INSERT INTO models (MakeID, modelName) VALUES (69, ' SA')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Crown Comfort')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Mega Cruiser')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Soarer')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Chaser')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Vanguard')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Mark X ZiO')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Land Cruiser Prado')
INSERT INTO models (MakeID, modelName) VALUES (69, ' TownAce')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Vista')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Motor Triathlon Race Car')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Gaia')
INSERT INTO models (MakeID, modelName) VALUES (69, ' GT-One')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Starlet GT Turbo')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Crown Majesta')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Celica GT-Four')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Cresta')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Pod')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Carina')
INSERT INTO models (MakeID, modelName) VALUES (69, ' MR2')
INSERT INTO models (MakeID, modelName) VALUES (69, ' FT-HS')
INSERT INTO models (MakeID, modelName) VALUES (69, ' AE85')
INSERT INTO models (MakeID, modelName) VALUES (69, ' G1')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Trekker')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Opa')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Sprinter')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Revo')
INSERT INTO models (MakeID, modelName) VALUES (69, ' RAV4 EV')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Yaris Verso')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Corona')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Publica')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Carina')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Corona EXiV')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Classic')
INSERT INTO models (MakeID, modelName) VALUES (69, ' i-unit')
INSERT INTO models (MakeID, modelName) VALUES (69, ' 2000GT')
INSERT INTO models (MakeID, modelName) VALUES (69, ' T100')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Kijang')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Platz')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Grand Hiace')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Camry TS-01')
INSERT INTO models (MakeID, modelName) VALUES (69, ' eCom')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Progrès')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Corolla')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Voltz')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Carina II')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Hybrid X')
INSERT INTO models (MakeID, modelName) VALUES (69, ' LiteAce')
INSERT INTO models (MakeID, modelName) VALUES (69, ' 4500GT')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Corolla Verso')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Mark II Blit')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Limo')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Verossa')
INSERT INTO models (MakeID, modelName) VALUES (69, ' FTX')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Sportivo Coupe')
INSERT INTO models (MakeID, modelName) VALUES (69, ' AA')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Dyna')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Regius')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Camry Solara')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Camry Hybrid')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Curren')
INSERT INTO models (MakeID, modelName) VALUES (69, ' MasterAce')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Sports 800')
INSERT INTO models (MakeID, modelName) VALUES (69, ' 4Runner')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Caldina')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Granvia')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Cressida')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Prius v')
INSERT INTO models (MakeID, modelName) VALUES (69, ' Mark II')
INSERT INTO models (MakeID, modelName) VALUES (69, ' WiLL')