INSERT INTO models (MakeID, modelName) VALUES (67, ' Wrx')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Legacy')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Outback')
INSERT INTO models (MakeID, modelName) VALUES (67, ' XV')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Wrx Sti')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Levorg')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Stella')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Forester')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Impreza')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Rex')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Legacy 5th Generation')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Legacy Sedan')
INSERT INTO models (MakeID, modelName) VALUES (67, ' 360')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Leone')
INSERT INTO models (MakeID, modelName) VALUES (67, ' 1000')
INSERT INTO models (MakeID, modelName) VALUES (67, ' BRAT')
INSERT INTO models (MakeID, modelName) VALUES (67, ' B9 Scrambler')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Sumo')
INSERT INTO models (MakeID, modelName) VALUES (67, ' R1')
INSERT INTO models (MakeID, modelName) VALUES (67, ' 1500')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Viziv Concept')
INSERT INTO models (MakeID, modelName) VALUES (67, ' XV Crosstrek')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Sti Wagon')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Cross Sport')
INSERT INTO models (MakeID, modelName) VALUES (67, ' BRZ')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Forester X 2008')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Forester 2013')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Exiga')
INSERT INTO models (MakeID, modelName) VALUES (67, ' impreza RB5')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Impreza RB320')
INSERT INTO models (MakeID, modelName) VALUES (67, ' B9sc')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Impreza WRX WRP10')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Loyale')
INSERT INTO models (MakeID, modelName) VALUES (67, ' R1e')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Pleo')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Sambar')
INSERT INTO models (MakeID, modelName) VALUES (67, ' XT')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Vivio')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Tribeca')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Justy')
INSERT INTO models (MakeID, modelName) VALUES (67, ' FF-1 Star')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Baja')
INSERT INTO models (MakeID, modelName) VALUES (67, ' G')
INSERT INTO models (MakeID, modelName) VALUES (67, ' R2')
INSERT INTO models (MakeID, modelName) VALUES (67, ' Alcyone SVX')
INSERT INTO models (MakeID, modelName) VALUES (67, ' R-2')