INSERT INTO models (MakeID, modelName) Values ( 3 , '105 Series Coupes' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '105/115 series coupes' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '12C' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '14' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '145' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '146' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '147' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '155' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '156' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '159' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '164' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '166' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '169' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '1750 Berlina' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '1750' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '1900' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '20/30 HP ES Sport' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '20/30 HP' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '2000 Berlina' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '2000' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '24 HP' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '2600' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '33 Stradale' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '33' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '33.2' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '40/60 GP' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '40/60 HP' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '4C COUPE(2013–present)-2-door coupe' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '4C LAUNCH EDITION(2013)' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '4C SPIDER(2013–present)-2-door roadster' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '6C' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '75 / Milano' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '8C Competizione');
INSERT INTO models (MakeID, modelName) Values ( 3 , '8C Spider' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '8C' );
INSERT INTO models (MakeID, modelName) Values ( 3 , '90' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Alfa 6' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Alfasud' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Alfetta' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Arna' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Brera and Spider' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Disco Volante' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'G1' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'GIULIA QUADRIFOGLIO' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'GTA' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'GTA' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'GTV and Spider' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'GTV6' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Giulia Compact-executive car' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Giulia TZ' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Giulia' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Giulietta(2010–present)-5-door hatchback' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Gran Sport Quattroruote' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Kamal' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Matta' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'MiTo' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Montreal' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'P1' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'P2' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'P3' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'RL' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'RM' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'SZ' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Scighera' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Spider' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Sprint' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Stelvio' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Tipo 308' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Tipo 33' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Tipo 512' );
INSERT INTO models (MakeID, modelName) Values ( 3 , 'Tipo A' );