INSERT INTO models (MakeID, modelName) VALUES (44, ' GLA Class')
INSERT INTO models (MakeID, modelName) VALUES (44, ' SL Class')
INSERT INTO models (MakeID, modelName) VALUES (44, ' AMG GT')
INSERT INTO models (MakeID, modelName) VALUES (44, ' A Class')
INSERT INTO models (MakeID, modelName) VALUES (44, ' B Class')
INSERT INTO models (MakeID, modelName) VALUES (44, ' C Class')
INSERT INTO models (MakeID, modelName) VALUES (44, ' CLA Class')
INSERT INTO models (MakeID, modelName) VALUES (44, ' CLS Class')
INSERT INTO models (MakeID, modelName) VALUES (44, ' E Class')
INSERT INTO models (MakeID, modelName) VALUES (44, ' G Class')
INSERT INTO models (MakeID, modelName) VALUES (44, ' GL Class')
INSERT INTO models (MakeID, modelName) VALUES (44, ' S Class')
INSERT INTO models (MakeID, modelName) VALUES (44, ' SLK Class')
INSERT INTO models (MakeID, modelName) VALUES (44, ' E Class Cabriolet')
INSERT INTO models (MakeID, modelName) VALUES (44, ' E Class Coupe')
INSERT INTO models (MakeID, modelName) VALUES (44, ' 300D')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W126')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W112')
INSERT INTO models (MakeID, modelName) VALUES (44, ' Mannheim 370')
INSERT INTO models (MakeID, modelName) VALUES (44, ' 260 D')
INSERT INTO models (MakeID, modelName) VALUES (44, ' 170 H')
INSERT INTO models (MakeID, modelName) VALUES (44, ' 500K')
INSERT INTO models (MakeID, modelName) VALUES (44, ' E Class Sedan')
INSERT INTO models (MakeID, modelName) VALUES (44, ' E Class Wagon')
INSERT INTO models (MakeID, modelName) VALUES (44, ' G Class SUV')
INSERT INTO models (MakeID, modelName) VALUES (44, ' CLA Class Coupe')
INSERT INTO models (MakeID, modelName) VALUES (44, ' GL Class SUV')
INSERT INTO models (MakeID, modelName) VALUES (44, ' GLE')
INSERT INTO models (MakeID, modelName) VALUES (44, ' GLA Class SUV')
INSERT INTO models (MakeID, modelName) VALUES (44, ' GLC Class')
INSERT INTO models (MakeID, modelName) VALUES (44, ' GLK Class SUV')
INSERT INTO models (MakeID, modelName) VALUES (44, ' M Class SUV')
INSERT INTO models (MakeID, modelName) VALUES (44, ' AMG GT S')
INSERT INTO models (MakeID, modelName) VALUES (44, ' S Class Coupe')
INSERT INTO models (MakeID, modelName) VALUES (44, ' S Class Sedan')
INSERT INTO models (MakeID, modelName) VALUES (44, ' SL Class Roadster')
INSERT INTO models (MakeID, modelName) VALUES (44, ' SLK Class Roadster')
INSERT INTO models (MakeID, modelName) VALUES (44, ' F-CELL Roadster')
INSERT INTO models (MakeID, modelName) VALUES (44, ' SS')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W201')
INSERT INTO models (MakeID, modelName) VALUES (44, '  2-Litres')
INSERT INTO models (MakeID, modelName) VALUES (44, ' 450SEL 6.9')
INSERT INTO models (MakeID, modelName) VALUES (44, ' SLS AMG')
INSERT INTO models (MakeID, modelName) VALUES (44, ' Sprinter')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W126')
INSERT INTO models (MakeID, modelName) VALUES (44, '  28/95')
INSERT INTO models (MakeID, modelName) VALUES (44, ' SLS Class')
INSERT INTO models (MakeID, modelName) VALUES (44, ' R107 and C107')
INSERT INTO models (MakeID, modelName) VALUES (44, ' CLK-Class')
INSERT INTO models (MakeID, modelName) VALUES (44, ' F-Cell')
INSERT INTO models (MakeID, modelName) VALUES (44, ' 200')
INSERT INTO models (MakeID, modelName) VALUES (44, ' C300 Sport')
INSERT INTO models (MakeID, modelName) VALUES (44, ' AMG')
INSERT INTO models (MakeID, modelName) VALUES (44, ' C-Class 350 Sport')
INSERT INTO models (MakeID, modelName) VALUES (44, ' R129')
INSERT INTO models (MakeID, modelName) VALUES (44, ' Stuttgart 200')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W221')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W111')
INSERT INTO models (MakeID, modelName) VALUES (44, ' 600')
INSERT INTO models (MakeID, modelName) VALUES (44, ' CL-Class')
INSERT INTO models (MakeID, modelName) VALUES (44, ' C300 Luxury')
INSERT INTO models (MakeID, modelName) VALUES (44, ' S-Class Hybrid')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W125')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W123')
INSERT INTO models (MakeID, modelName) VALUES (44, ' SLR McLaren')
INSERT INTO models (MakeID, modelName) VALUES (44, ' Viano')
INSERT INTO models (MakeID, modelName) VALUES (44, '  170 V')
INSERT INTO models (MakeID, modelName) VALUES (44, ' 130')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W108')
INSERT INTO models (MakeID, modelName) VALUES (44, ' 190SL')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W163 Grand Prix')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W31')
INSERT INTO models (MakeID, modelName) VALUES (44, ' Stuttgart 260')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W120')
INSERT INTO models (MakeID, modelName) VALUES (44, ' C63 AMG Sedan')
INSERT INTO models (MakeID, modelName) VALUES (44, ' 150')
INSERT INTO models (MakeID, modelName) VALUES (44, ' 400')
INSERT INTO models (MakeID, modelName) VALUES (44, ' 300SL')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W219')
INSERT INTO models (MakeID, modelName) VALUES (44, ' 320')
INSERT INTO models (MakeID, modelName) VALUES (44, ' 770')
INSERT INTO models (MakeID, modelName) VALUES (44, ' Vito')
INSERT INTO models (MakeID, modelName) VALUES (44, ' 370S')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W18')
INSERT INTO models (MakeID, modelName) VALUES (44, ' 200 Lang')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W143')
INSERT INTO models (MakeID, modelName) VALUES (44, ' Velo')
INSERT INTO models (MakeID, modelName) VALUES (44, ' Vaneo')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W114')
INSERT INTO models (MakeID, modelName) VALUES (44, ' V-Class')
INSERT INTO models (MakeID, modelName) VALUES (44, ' CLK GTR')
INSERT INTO models (MakeID, modelName) VALUES (44, ' 380K')
INSERT INTO models (MakeID, modelName) VALUES (44, ' R-Class')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W163')
INSERT INTO models (MakeID, modelName) VALUES (44, ' Tropfenwagen')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W124')
INSERT INTO models (MakeID, modelName) VALUES (44, ' 35 hp')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W164')
INSERT INTO models (MakeID, modelName) VALUES (44, ' C300 Luxury 4MATIC')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W10')
INSERT INTO models (MakeID, modelName) VALUES (44, ' C300 Sport 4MATIC')
INSERT INTO models (MakeID, modelName) VALUES (44, ' W212')
INSERT INTO models (MakeID, modelName) VALUES (44, ' K')
INSERT INTO models (MakeID, modelName) VALUES (44, ' 540K')
INSERT INTO models (MakeID, modelName) VALUES (44, ' CLC-Class')