INSERT INTO models (MakeID, modelName) VALUES (12, 'Captiva')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Trax')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Suburban')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Spark')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Impala')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Sail')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Cruze')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Camaro')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Corvette')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Colorado')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Equinox')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Spin')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Trailblazer')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Chevelle')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Caprice')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Cobalt')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Aveo')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Orlando')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Citation')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Silverado')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Yeoman')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Montana')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Omega')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Express')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Malibu (1964 – present)')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Traverse (2008 – present)')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Chevette')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Tahoe')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Avalanche (2001 – 2013)')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Volt')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Aerovette')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Astrovette')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Bel Air')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Testudo')
INSERT INTO models (MakeID, modelName) VALUES (12, 'SS')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Series M Copper-Cooled')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Sequel')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Nomad')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Miray')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Bolt')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Agile')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Corvette Stingray')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Corvair Monza GT')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Cheyenne')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Bolt')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Mako Shark Concept')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Sonic')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Cobalt SS')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Celebrity')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Corvair')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Vega')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Chevy II / Nova')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Cavalier')
INSERT INTO models (MakeID, modelName) VALUES (12, 'HHR')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Monza')
INSERT INTO models (MakeID, modelName) VALUES (12, 'C6')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Corvette C1')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Corvette C4')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Corvette C6 ZR1')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Corvette Convertible')
INSERT INTO models (MakeID, modelName) VALUES (12, 'SSR')
INSERT INTO models (MakeID, modelName) VALUES (12, 'C/K')
INSERT INTO models (MakeID, modelName) VALUES (12, 'LUV')
INSERT INTO models (MakeID, modelName) VALUES (12, 'S-10')
INSERT INTO models (MakeID, modelName) VALUES (12, 'S-10 Blazer')
INSERT INTO models (MakeID, modelName) VALUES (12, 'El Camino')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Monte Carlo')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Uplander')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Lumina')
INSERT INTO models (MakeID, modelName) VALUES (12, '150')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Nova SS')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Geo Spectrum')
INSERT INTO models (MakeID, modelName) VALUES (12, 'K5 Blazer')
INSERT INTO models (MakeID, modelName) VALUES (12, 'SSR')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Corvette Mako Shark')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Tracker')
INSERT INTO models (MakeID, modelName) VALUES (12, '400')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Constantia')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Chevelle Laguna')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Firenza CanAm')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Opala')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Delray')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Greenbrier')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Chevelle COPO 427')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Maruti Versa')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Cosworth Vega')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Superior')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Corvair 500')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Caprice LS')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Marajó')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Titan')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Geo Metro')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Corvair 900 Monza')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Cerv 1')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Fleetline')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Sprint')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Kingswood')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Parkwood')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Impala SS')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Geo Prizm')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Geo Sprint')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Bison')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Styleline')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Saturn Astra')
INSERT INTO models (MakeID, modelName) VALUES (12, '210')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Celta')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Task Force')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Advance Design')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Beretta')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Lumina APV')
INSERT INTO models (MakeID, modelName) VALUES (12, 'S-10 EV')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Holden Caprice')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Kadett')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Astro')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Bruin')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Townsman')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Apache')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Lumina Z34')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Maruti Esteem')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Venture')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Lakewood')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Biscayne')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Corsica')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Kodiak')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Beauville')
INSERT INTO models (MakeID, modelName) VALUES (12, 'Yenko Camaro')