INSERT INTO models (MakeID, modelName) VALUES (1 , '1000 Berlina Corsa');
INSERT INTO models (MakeID, modelName) VALUES (1 , '1000 Berlina');
INSERT INTO models (MakeID, modelName) VALUES (1 , '1000 Bialbero Zagato');
INSERT INTO models (MakeID, modelName) VALUES (1 , '1000 TCR Berlina Corsa');
INSERT INTO models (MakeID, modelName) VALUES (1 , '1000 TCR Berlina');
INSERT INTO models (MakeID, modelName) VALUES (1 , '1000');
INSERT INTO models (MakeID, modelName) VALUES (1 , '1000TC Berlina Corsa');
INSERT INTO models (MakeID, modelName) VALUES (1 , '1100 Scorpione Spider (Boano)');
INSERT INTO models (MakeID, modelName) VALUES (1 , '124 Rally');
INSERT INTO models (MakeID, modelName) VALUES (1 , '124 Spider');
INSERT INTO models (MakeID, modelName) VALUES (1 , '1300 Scorpione');
INSERT INTO models (MakeID, modelName) VALUES (1 , '1500 Biposto');
INSERT INTO models (MakeID, modelName) VALUES (1 , '2000 Coupe');
INSERT INTO models (MakeID, modelName) VALUES (1 , '204A Berlinetta');
INSERT INTO models (MakeID, modelName) VALUES (1 , '205 Monza');
INSERT INTO models (MakeID, modelName) VALUES (1 , '205A Berlinetta');
INSERT INTO models (MakeID, modelName) VALUES (1 , '205A');
INSERT INTO models (MakeID, modelName) VALUES (1 , '207A Spyder');
INSERT INTO models (MakeID, modelName) VALUES (1 , '209A Boano Coupe');
INSERT INTO models (MakeID, modelName) VALUES (1 , '2200');
INSERT INTO models (MakeID, modelName) VALUES (1 , '2400');
INSERT INTO models (MakeID, modelName) VALUES (1 , '3000 Prototipo');
INSERT INTO models (MakeID, modelName) VALUES (1 , '500');
INSERT INTO models (MakeID, modelName) VALUES (1 , '595 Esseesse');
INSERT INTO models (MakeID, modelName) VALUES (1 , '595 Pista');
INSERT INTO models (MakeID, modelName) VALUES (1 , '595 SS');
INSERT INTO models (MakeID, modelName) VALUES (1 , '595 Turismo');
INSERT INTO models (MakeID, modelName) VALUES (1 , '595');
INSERT INTO models (MakeID, modelName) VALUES (1 , '695 70th ANNIVERSARIO');
INSERT INTO models (MakeID, modelName) VALUES (1 , '695 SS');
INSERT INTO models (MakeID, modelName) VALUES (1 , '750 Berlina (Derivazione)');
INSERT INTO models (MakeID, modelName) VALUES (1 , '750 GT Zagato');
INSERT INTO models (MakeID, modelName) VALUES (1 , '750 Zagato Monza');
INSERT INTO models (MakeID, modelName) VALUES (1 , '750');
INSERT INTO models (MakeID, modelName) VALUES (1 , '850 Allemano coupe');
INSERT INTO models (MakeID, modelName) VALUES (1 , '850TC Berlina');
INSERT INTO models (MakeID, modelName) VALUES (1 , '850TC Corsa');
INSERT INTO models (MakeID, modelName) VALUES (1 , '850TC Nürburgring Corsa');
INSERT INTO models (MakeID, modelName) VALUES (1 , '850TC Nürburgring');
INSERT INTO models (MakeID, modelName) VALUES (1 , 'Allemano 750 Spider');
INSERT INTO models (MakeID, modelName) VALUES (1 , 'Autobianchi A112 70HP');
INSERT INTO models (MakeID, modelName) VALUES (1 , 'Grande Punto SS');
INSERT INTO models (MakeID, modelName) VALUES (1 , 'Grande Punto');
INSERT INTO models (MakeID, modelName) VALUES (1 , 'Monomille');
INSERT INTO models (MakeID, modelName) VALUES (1 , 'OT 1000');
INSERT INTO models (MakeID, modelName) VALUES (1 , 'OT 1300');
INSERT INTO models (MakeID, modelName) VALUES (1 , 'OT 1600');
INSERT INTO models (MakeID, modelName) VALUES (1 , 'OT 2000 Competition Coupe');
INSERT INTO models (MakeID, modelName) VALUES (1 , 'Punto Evo');
INSERT INTO models (MakeID, modelName) VALUES (1 , 'Punto Supersport');
INSERT INTO models (MakeID, modelName) VALUES (1 , 'Simca 1300 GT');
INSERT INTO models (MakeID, modelName) VALUES (1 , 'Simca 2000');
INSERT INTO models (MakeID, modelName) VALUES (1 , 'Zagato 750');