INSERT INTO models (MakeID, modelName) Values (5 , '12/50 Standard' );
INSERT INTO models (MakeID, modelName) Values (5 , '15/98' );
INSERT INTO models (MakeID, modelName) Values (5 , '2 Litre Speed' );
INSERT INTO models (MakeID, modelName) Values (5 , '2 litre C-Type' );
INSERT INTO models (MakeID, modelName) Values (5 , '2-Litre Sports' );
INSERT INTO models (MakeID, modelName) Values (5 , 'CC100' );
INSERT INTO models (MakeID, modelName) Values (5 , 'Cygnet (Hatchback – 2011-2012)' );
INSERT INTO models (MakeID, modelName) Values (5 , 'DB AR1' );
INSERT INTO models (MakeID, modelName) Values (5 , 'DB Mark III' );
INSERT INTO models (MakeID, modelName) Values (5 , 'DB11 Coupe' );
INSERT INTO models (MakeID, modelName) Values (5 , 'DB2' );
INSERT INTO models (MakeID, modelName) Values (5 , 'DB2/4' );
INSERT INTO models (MakeID, modelName) Values (5 , 'DB3' );
INSERT INTO models (MakeID, modelName) Values (5 , 'DB4 GT Zagato' );
INSERT INTO models (MakeID, modelName) Values (5 , 'DB4' );
INSERT INTO models (MakeID, modelName) Values (5 , 'DB5' );
INSERT INTO models (MakeID, modelName) Values (5 , 'DB6' );
INSERT INTO models (MakeID, modelName) Values (5 , 'DB7 Zagato' );
INSERT INTO models (MakeID, modelName) Values (5 , 'DB7' );
INSERT INTO models (MakeID, modelName) Values (5 , 'DB9' );
INSERT INTO models (MakeID, modelName) Values (5 , 'DBS Coupe (2-door Coupe – 2007-2012)' );
INSERT INTO models (MakeID, modelName) Values (5 , 'DBS V12' );
INSERT INTO models (MakeID, modelName) Values (5 , 'DBS Volante (2-door Coupe – 2009-2012)' );
INSERT INTO models (MakeID, modelName) Values (5 , 'DBS' );
INSERT INTO models (MakeID, modelName) Values (5 , 'First Series' );
INSERT INTO models (MakeID, modelName) Values (5 , 'Halford Special' );
INSERT INTO models (MakeID, modelName) Values (5 , 'International Le Mans' );
INSERT INTO models (MakeID, modelName) Values (5 , 'Lagonda 3-Litre' );
INSERT INTO models (MakeID, modelName) Values (5 , 'Lagonda Rapide' );
INSERT INTO models (MakeID, modelName) Values (5 , 'Lagonda' );
INSERT INTO models (MakeID, modelName) Values (5 , 'Le Mans' );
INSERT INTO models (MakeID, modelName) Values (5 , 'Mark II' );
INSERT INTO models (MakeID, modelName) Values (5 , 'One 77' );
INSERT INTO models (MakeID, modelName) Values (5 , 'Rapide S' );
INSERT INTO models (MakeID, modelName) Values (5 , 'Rapide' );
INSERT INTO models (MakeID, modelName) Values (5 , 'Short Chassis Volante' );
INSERT INTO models (MakeID, modelName) Values (5 , 'Standard Sports' );
INSERT INTO models (MakeID, modelName) Values (5 , 'Ulster' );
INSERT INTO models (MakeID, modelName) Values (5 , 'V12 Vanquish S' );
INSERT INTO models (MakeID, modelName) Values (5 , 'V12 Zagato (Coupe – 2011-2012)' );
INSERT INTO models (MakeID, modelName) Values (5 , 'V8 Vantage S' );
INSERT INTO models (MakeID, modelName) Values (5 , 'V8 Zagato' );
INSERT INTO models (MakeID, modelName) Values (5 , 'V8' );
INSERT INTO models (MakeID, modelName) Values (5 , 'Vanquish S' );
INSERT INTO models (MakeID, modelName) Values (5 , 'Vanquish' );
INSERT INTO models (MakeID, modelName) Values (5 , 'Vantage' );
INSERT INTO models (MakeID, modelName) Values (5 , 'Virage' );