INSERT INTO models (MakeID, modelName) VALUES (18, 'Wake')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Naked')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Tanto')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Move')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Esse')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Leeza')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Mira Gino')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Charmant')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Rocky')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Mebius')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Compagno')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Sonica')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Rugger')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Charade')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Copen')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Storia')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Luxio')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Tanto Exe')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Pyzar')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Fellow Max')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Consorte')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Materia')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Ayla')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Taft')
INSERT INTO models (MakeID, modelName) VALUES (18, 'YRV')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Terios')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Bee')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Boon')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Midget')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Applause')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Hijet')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Mira')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Hijet Caddie')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Opti Mk 1')
INSERT INTO models (MakeID, modelName) VALUES (18, 'Rocky 4WD')