INSERT INTO models (MakeID, modelName) VALUES (74, ' V40')
INSERT INTO models (MakeID, modelName) VALUES (74, ' V90')
INSERT INTO models (MakeID, modelName) VALUES (74, ' XC90')
INSERT INTO models (MakeID, modelName) VALUES (74, ' S90')
INSERT INTO models (MakeID, modelName) VALUES (74, ' S80')
INSERT INTO models (MakeID, modelName) VALUES (74, ' V60')
INSERT INTO models (MakeID, modelName) VALUES (74, ' XC70')
INSERT INTO models (MakeID, modelName) VALUES (74, ' XC60')
INSERT INTO models (MakeID, modelName) VALUES (74, ' 480')
INSERT INTO models (MakeID, modelName) VALUES (74, ' C70 ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' C30 ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' S40 ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' V40 Cross Country')
INSERT INTO models (MakeID, modelName) VALUES (74, ' S60 ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' V90 Cross Country')
INSERT INTO models (MakeID, modelName) VALUES (74, ' 140 Series')
INSERT INTO models (MakeID, modelName) VALUES (74, ' 200 Series')
INSERT INTO models (MakeID, modelName) VALUES (74, ' 850')
INSERT INTO models (MakeID, modelName) VALUES (74, ' PV801-10')
INSERT INTO models (MakeID, modelName) VALUES (74, ' PV51-57')
INSERT INTO models (MakeID, modelName) VALUES (74, ' V50 ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' 440/460')
INSERT INTO models (MakeID, modelName) VALUES (74, ' 164')
INSERT INTO models (MakeID, modelName) VALUES (74, ' YCC ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' VESC ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' Venus Bilo ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' T6 ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' Tundra ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' SCC ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' Philip')
INSERT INTO models (MakeID, modelName) VALUES (74, ' GTZ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' ECC ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' Concept You ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' Concept XC Coupe')
INSERT INTO models (MakeID, modelName) VALUES (74, ' Concept Estate')
INSERT INTO models (MakeID, modelName) VALUES (74, ' Concept Coupe')
INSERT INTO models (MakeID, modelName) VALUES (74, ' City Taxi ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' ACC ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' ACC2 ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' EC ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' Elisabeth I ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' LCP2000 ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' Margarete Rose ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' PCC ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' PCC2 ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' ReCharge Concept ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' S60 Concept ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' Universe Concept ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' VCC ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' XC60 Concept ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' 1800 ESC')
INSERT INTO models (MakeID, modelName) VALUES (74, ' 3CC ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' Amazon/122 ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' C202 ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' C3-series ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' Duett ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' PV51 ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' PV650 Series')
INSERT INTO models (MakeID, modelName) VALUES (74, ' PV444/544 ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' PV800 Series ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' PV 36 Carioca ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' PV 60 ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' P1900 ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' TR670 Series ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' 66 ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' ÖV 4 ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' 700 Series')
INSERT INTO models (MakeID, modelName) VALUES (74, ' P1800 ')
INSERT INTO models (MakeID, modelName) VALUES (74, ' L3314')
INSERT INTO models (MakeID, modelName) VALUES (74, ' PV821-4')
delete  from makes where makeName = 'Rimac';