INSERT INTO models (MakeID, modelName) VALUES (66, ' Tivoli')
INSERT INTO models (MakeID, modelName) VALUES (66, ' Rodius')
INSERT INTO models (MakeID, modelName) VALUES (66, ' Korando')
INSERT INTO models (MakeID, modelName) VALUES (66, ' Chairman')
INSERT INTO models (MakeID, modelName) VALUES (66, ' Actyon')
INSERT INTO models (MakeID, modelName) VALUES (66, ' Istana')
INSERT INTO models (MakeID, modelName) VALUES (66, ' Rexton')
INSERT INTO models (MakeID, modelName) VALUES (66, ' Kyron')
INSERT INTO models (MakeID, modelName) VALUES (66, ' Musso')
INSERT INTO models (MakeID, modelName) VALUES (66, ' Korando Family')
INSERT INTO models (MakeID, modelName) VALUES (66, ' Rexton II')
INSERT INTO models (MakeID, modelName) VALUES (66, ' Rexton W')
INSERT INTO models (MakeID, modelName) VALUES (66, ' Tivoli XLV')
INSERT INTO models (MakeID, modelName) VALUES (66, ' Actyon Sports')
INSERT INTO models (MakeID, modelName) VALUES (66, ' Musso Sports')
INSERT INTO models (MakeID, modelName) VALUES (66, ' Chairman H')
INSERT INTO models (MakeID, modelName) VALUES (66, ' Chairman W')
INSERT INTO models (MakeID, modelName) VALUES (66, ' Kallista')
INSERT INTO models (MakeID, modelName) VALUES (66, ' DA Truck')
INSERT INTO models (MakeID, modelName) VALUES (66, ' SY Truck')
INSERT INTO models (MakeID, modelName) VALUES (66, ' Transtar')