INSERT INTO models (MakeID, modelName) VALUES (14, 'Ami')
INSERT INTO models (MakeID, modelName) VALUES (14, 'C3')
INSERT INTO models (MakeID, modelName) VALUES (14, 'C4 Sedan')
INSERT INTO models (MakeID, modelName) VALUES (14, 'C6 II')
INSERT INTO models (MakeID, modelName) VALUES (14, 'C-Elysee')
INSERT INTO models (MakeID, modelName) VALUES (14, 'Space Tourer')
INSERT INTO models (MakeID, modelName) VALUES (14, 'Berlingo')
INSERT INTO models (MakeID, modelName) VALUES (14, 'C3 Aircross')
INSERT INTO models (MakeID, modelName) VALUES (14, 'C3-XR')
INSERT INTO models (MakeID, modelName) VALUES (14, 'C4')
INSERT INTO models (MakeID, modelName) VALUES (14, 'C5 Aircorss')
INSERT INTO models (MakeID, modelName) VALUES (14, 'Jumpy')
INSERT INTO models (MakeID, modelName) VALUES (14, 'Jumper')
INSERT INTO models (MakeID, modelName) VALUES (14, 'Axel')
INSERT INTO models (MakeID, modelName) VALUES (14, 'AX')
INSERT INTO models (MakeID, modelName) VALUES (14, 'BX')
INSERT INTO models (MakeID, modelName) VALUES (14, 'C Crosser')
INSERT INTO models (MakeID, modelName) VALUES (14, 'C1')
INSERT INTO models (MakeID, modelName) VALUES (14, 'C2')
INSERT INTO models (MakeID, modelName) VALUES (14, 'C-Triomphe')
INSERT INTO models (MakeID, modelName) VALUES (14, 'C5')
INSERT INTO models (MakeID, modelName) VALUES (14, 'C6')
INSERT INTO models (MakeID, modelName) VALUES (14, 'C4')
INSERT INTO models (MakeID, modelName) VALUES (14, 'C8')
INSERT INTO models (MakeID, modelName) VALUES (14, 'E-Mehari')
INSERT INTO models (MakeID, modelName) VALUES (14, 'Evasion')
INSERT INTO models (MakeID, modelName) VALUES (14, 'Fukang')
INSERT INTO models (MakeID, modelName) VALUES (14, 'Saxo')
INSERT INTO models (MakeID, modelName) VALUES (14, 'Visa')
INSERT INTO models (MakeID, modelName) VALUES (14, 'XM')
INSERT INTO models (MakeID, modelName) VALUES (14, 'Xantia')
INSERT INTO models (MakeID, modelName) VALUES (14, 'Xsara')
INSERT INTO models (MakeID, modelName) VALUES (14, 'DS3')
INSERT INTO models (MakeID, modelName) VALUES (14, 'DS4')
INSERT INTO models (MakeID, modelName) VALUES (14, 'DS5')
INSERT INTO models (MakeID, modelName) VALUES (14, 'Nemo')