INSERT INTO models (MakeID, modelName) VALUES (73, ' Beetle')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Golf')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Touran')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Jetta')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Tiguan')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Passat')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Polo GTI')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Atlas')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Touareg')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Caddy')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Transporter')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Sharan')
INSERT INTO models (MakeID, modelName) VALUES (73, ' CC')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Scirocco')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Lavida')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Type 4')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Type 3')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Eos')
INSERT INTO models (MakeID, modelName) VALUES (73, ' K70')
INSERT INTO models (MakeID, modelName) VALUES (73, ' up!')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Santana')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Corrado')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Derby')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Polo')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Citi Golf')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Golf GTI ')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Polo Mk III')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Polo Mk5')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Polo Mk IV')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Polo Playa')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Golf Mk1')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Golf Mk2')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Golf Mk3')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Golf Mk4')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Concept BlueSport')
INSERT INTO models (MakeID, modelName) VALUES (73, ' GTI')
INSERT INTO models (MakeID, modelName) VALUES (73, ' SP2')
INSERT INTO models (MakeID, modelName) VALUES (73, ' 1-litre car')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Golf Mk5')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Golf Mk6')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Golf Variant')
INSERT INTO models (MakeID, modelName) VALUES (73, ' New Beetle')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Gol')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Phaeton')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Fox')
INSERT INTO models (MakeID, modelName) VALUES (73, ' LT')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Type 147 Kleinlieferwagen')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Type 2 (T3)')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Crafter')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Type 2')
INSERT INTO models (MakeID, modelName) VALUES (73, ' California')
INSERT INTO models (MakeID, modelName) VALUES (73, ' GLI')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Polo Hatchback')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Polo Sedan')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Routan')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Concept BlueSport')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Amarok')
INSERT INTO models (MakeID, modelName) VALUES (73, ' R32')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Kübelwagen')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Iltis')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Iroc')
INSERT INTO models (MakeID, modelName) VALUES (73, ' ARVW')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Delivery')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Brasilia')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Country Buggy')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Lupo')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Bio Runner')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Thing')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Apollo')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Karmann Ghia')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Lavida')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Type 14A')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Type 18A')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Golf Cabriolet')
INSERT INTO models (MakeID, modelName) VALUES (73, ' W12')
INSERT INTO models (MakeID, modelName) VALUES (73, ' EA489 Basistransporter')
INSERT INTO models (MakeID, modelName) VALUES (73, ' 181')
INSERT INTO models (MakeID, modelName) VALUES (73, ' 276 Schlepperfahrzeug')
INSERT INTO models (MakeID, modelName) VALUES (73, ' Constellation')