INSERT INTO models (MakeID, modelName) VALUES (41, ' Quattroporte')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Ghibli')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Levante')
INSERT INTO models (MakeID, modelName) VALUES (41, ' GranTurismo')
INSERT INTO models (MakeID, modelName) VALUES (41, ' GranCabrio')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Shamal')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Mistral')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Barchetta')
INSERT INTO models (MakeID, modelName) VALUES (41, ' 3500 GT')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Ghibli S Q4')
INSERT INTO models (MakeID, modelName) VALUES (41, ' GranTurismo Sport')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Quattroporte S')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Quattroporte Diesel')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Ghibli S')
INSERT INTO models (MakeID, modelName) VALUES (41, ' GranCabrio MC Centennial Edition')
INSERT INTO models (MakeID, modelName) VALUES (41, ' GranTurismo MC Stradale')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Quattroporte S Q4')
INSERT INTO models (MakeID, modelName) VALUES (41, ' GranTurismo MC Centennial Edition')
INSERT INTO models (MakeID, modelName) VALUES (41, ' GranCabrio Sport')
INSERT INTO models (MakeID, modelName) VALUES (41, ' GranCabrio MC')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Quattroporte GTS')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Coupé / Spyder')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Khamsin')
INSERT INTO models (MakeID, modelName) VALUES (41, ' 3200 GT')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Sebring')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Kyalami')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Mexico')
INSERT INTO models (MakeID, modelName) VALUES (41, ' A6')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Biturbo')
INSERT INTO models (MakeID, modelName) VALUES (41, ' 420')
INSERT INTO models (MakeID, modelName) VALUES (41, ' MC12')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Merak')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Indy')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Tipo 61')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Karif')
INSERT INTO models (MakeID, modelName) VALUES (41, ' 75th Birdcage')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Bora')
INSERT INTO models (MakeID, modelName) VALUES (41, ' 5000 GT')
INSERT INTO models (MakeID, modelName) VALUES (41, ' 450S')
INSERT INTO models (MakeID, modelName) VALUES (41, ' 200S')
INSERT INTO models (MakeID, modelName) VALUES (41, ' 300S')
INSERT INTO models (MakeID, modelName) VALUES (41, ' 6CM')
INSERT INTO models (MakeID, modelName) VALUES (41, ' 8C')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Tipo 154')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Tipo 26M')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Tipo 151')
INSERT INTO models (MakeID, modelName) VALUES (41, ' V8RI')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Boomerang')
INSERT INTO models (MakeID, modelName) VALUES (41, ' 150S')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Spyder')
INSERT INTO models (MakeID, modelName) VALUES (41, ' 3500')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Racing')
INSERT INTO models (MakeID, modelName) VALUES (41, ' 350S')
INSERT INTO models (MakeID, modelName) VALUES (41, ' 250F')
INSERT INTO models (MakeID, modelName) VALUES (41, ' 430')
INSERT INTO models (MakeID, modelName) VALUES (41, ' 26M')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Birdcage 75th')
INSERT INTO models (MakeID, modelName) VALUES (41, ' 228')
INSERT INTO models (MakeID, modelName) VALUES (41, ' Gran Sport')