INSERT INTO models (MakeID, modelName) VALUES (48, ' Patrol')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Juke')
INSERT INTO models (MakeID, modelName) VALUES (48, ' X-TRAIL')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Altima')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Sylphy')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Grand Livina')
INSERT INTO models (MakeID, modelName) VALUES (48, ' NP300 / Navara')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Titan')
INSERT INTO models (MakeID, modelName) VALUES (48, ' NV350 Urvan Model')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Leaf')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Maxima')
INSERT INTO models (MakeID, modelName) VALUES (48, ' GT-R')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Almera')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Skyline')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Violet/Stanza')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Caravan / Urvan ')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Teana ')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Murano ')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Armada')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Elgrand ')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Patrol Super Safari')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Qashqai / Dualis')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Patrol Royale')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Lafesta Highway Star ')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Atlas / Cabstar')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Sentra/Tsuru/Sunny ')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Pathfinder/Terrano ')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Xterra ')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Note ')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Quest ')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Cube ')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Serena ')
INSERT INTO models (MakeID, modelName) VALUES (48, ' NPT-90 ')
INSERT INTO models (MakeID, modelName) VALUES (48, ' R383 ')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Fairlady Z ')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Fairlady Z / 370Z Coupe ')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Silvia')
INSERT INTO models (MakeID, modelName) VALUES (48, ' March / Micra ')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Rogue ')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Cedric')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Crew')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Leopard')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Cima')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Gloria')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Atleon')
INSERT INTO models (MakeID, modelName) VALUES (48, ' AD/AD Expert Model')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Fairlady Z Roadster / 370Z Roadster')
INSERT INTO models (MakeID, modelName) VALUES (48, ' NP200 Model')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Frontier Model')
INSERT INTO models (MakeID, modelName) VALUES (48, ' NV1500/NV2500 HD/NV3500 HD Model')
INSERT INTO models (MakeID, modelName) VALUES (48, ' NV200 VANETTE Model')
INSERT INTO models (MakeID, modelName) VALUES (48, ' NV350 Caravan Model')
INSERT INTO models (MakeID, modelName) VALUES (48, ' NV400 Model')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Primastar Model')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Versa / Latio')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Versa HB')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Wingroad')
INSERT INTO models (MakeID, modelName) VALUES (48, ' R390 GT1')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Avenir')
INSERT INTO models (MakeID, modelName) VALUES (48, ' NX')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Bevel')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Saurus Jr.')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Saurus')
INSERT INTO models (MakeID, modelName) VALUES (48, ' R’nessa')
INSERT INTO models (MakeID, modelName) VALUES (48, ' R90C')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Livina Geniss')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Diesel RN')
INSERT INTO models (MakeID, modelName) VALUES (48, ' R381')
INSERT INTO models (MakeID, modelName) VALUES (48, ' R89C')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Cedric Y31')
INSERT INTO models (MakeID, modelName) VALUES (48, ' R391')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Civilian')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Paladin')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Gloria Y31')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Vanette')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Cherry')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Figaro')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Pulsar GTI-R')
INSERT INTO models (MakeID, modelName) VALUES (48, ' 240SX')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Bluebird Sylphy')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Tiida')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Almera Tino')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Terrano II')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Hypermini')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Bluebird')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Stagea')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Altra')
INSERT INTO models (MakeID, modelName) VALUES (48, ' 280ZX')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Diesel Space Runner JP')
INSERT INTO models (MakeID, modelName) VALUES (48, ' 300C')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Prince Homer')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Prince Royal')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Bassara')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Homy')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Largo')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Liberty')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Ute')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Prince R380')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Rasheen')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Gazelle')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Diesel Space Runner RM')
INSERT INTO models (MakeID, modelName) VALUES (48, ' GTP ZX-Turbo')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Stanza')
INSERT INTO models (MakeID, modelName) VALUES (48, ' The Third Generation (Z31): 300ZX')
INSERT INTO models (MakeID, modelName) VALUES (48, ' S-Cargo')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Pao')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Sunny')
INSERT INTO models (MakeID, modelName) VALUES (48, ' S30')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Fuga')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Primera')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Z-car')
INSERT INTO models (MakeID, modelName) VALUES (48, ' President')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Presea')
INSERT INTO models (MakeID, modelName) VALUES (48, ' 350Z')
INSERT INTO models (MakeID, modelName) VALUES (48, ' R382')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Diesel Space Runner RP')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Be-1')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Presage')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Bluebird')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Bluebird (U12)')
INSERT INTO models (MakeID, modelName) VALUES (48, ' P35')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Diesel Quon')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Hardbody Truck')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Diesel Big Thumb')
INSERT INTO models (MakeID, modelName) VALUES (48, ' 180SX')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Cefiro')
INSERT INTO models (MakeID, modelName) VALUES (48, ' 200SX')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Diesel Condor')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Prairie')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Laurel')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Sileighty')
INSERT INTO models (MakeID, modelName) VALUES (48, ' Micra')