INSERT INTO models (MakeID, modelName) VALUES (46, ' Countryman')
INSERT INTO models (MakeID, modelName) VALUES (46, ' Cooper S Clubman')
INSERT INTO models (MakeID, modelName) VALUES (46, ' 5 Door')
INSERT INTO models (MakeID, modelName) VALUES (46, ' Paceman')
INSERT INTO models (MakeID, modelName) VALUES (46, ' Cooper S')
INSERT INTO models (MakeID, modelName) VALUES (46, ' Mk I Cooper')
INSERT INTO models (MakeID, modelName) VALUES (46, ' Mk II Cooper')
INSERT INTO models (MakeID, modelName) VALUES (46, ' Moke')
INSERT INTO models (MakeID, modelName) VALUES (46, ' Hatch')
INSERT INTO models (MakeID, modelName) VALUES (46, ' 3 Door')
INSERT INTO models (MakeID, modelName) VALUES (46, ' Clubman')
INSERT INTO models (MakeID, modelName) VALUES (46, ' Convertible')
INSERT INTO models (MakeID, modelName) VALUES (46, ' Morris Saloon De Luxe')
INSERT INTO models (MakeID, modelName) VALUES (46, ' Morris Cooper 1961')
INSERT INTO models (MakeID, modelName) VALUES (46, ' Austin Super Deluxe')
INSERT INTO models (MakeID, modelName) VALUES (46, ' Austin Saloon')
INSERT INTO models (MakeID, modelName) VALUES (46, ' Cooper')
INSERT INTO models (MakeID, modelName) VALUES (46, ' Cooper Countryman')
INSERT INTO models (MakeID, modelName) VALUES (46, ' Austin Saloon De Luxe')
