INSERT INTO models (MakeID, modelName) VALUES (72, ' Adam')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Firenza')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Astra')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Corsa')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Insignia')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Viva')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Astra VXR')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Corsa VXR')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Insignia VXR')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Cavalier')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Cresta')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Velox')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Victor')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Wyvern')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Chevette')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Antara')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Mokka')
INSERT INTO models (MakeID, modelName) VALUES (72, ' GTC')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Meriva')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Cascada')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Combo Tour')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Corsavan')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Combo')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Vivaro')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Movano')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Zafira Tourer')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Insignia VXR')
INSERT INTO models (MakeID, modelName) VALUES (72, ' VXR8 GTS')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Ten')
INSERT INTO models (MakeID, modelName) VALUES (72, ' 14-6')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Belmont')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Cadet VY and export VX')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Carlton')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Magnum')
INSERT INTO models (MakeID, modelName) VALUES (72, ' SRV')
INSERT INTO models (MakeID, modelName) VALUES (72, ' A-Type')
INSERT INTO models (MakeID, modelName) VALUES (72, ' 12/4')
INSERT INTO models (MakeID, modelName) VALUES (72, ' 14/6')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Corsavan')
INSERT INTO models (MakeID, modelName) VALUES (72, ' 30/98')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Six')
INSERT INTO models (MakeID, modelName) VALUES (72, ' 14/40')
INSERT INTO models (MakeID, modelName) VALUES (72, ' D-Type')
INSERT INTO models (MakeID, modelName) VALUES (72, ' 10-4')
INSERT INTO models (MakeID, modelName) VALUES (72, ' T')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Cadet')
INSERT INTO models (MakeID, modelName) VALUES (72, ' 20/60')
INSERT INTO models (MakeID, modelName) VALUES (72, ' 25/70')
INSERT INTO models (MakeID, modelName) VALUES (72, ' 25')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Astra MK2')
INSERT INTO models (MakeID, modelName) VALUES (72, ' 23/60')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Prince Henry')
INSERT INTO models (MakeID, modelName) VALUES (72, ' Wyvern')
INSERT INTO models (MakeID, modelName) VALUES (72, ' VX220')
INSERT INTO models (MakeID, modelName) VALUES (72, ' VXR8')