INSERT INTO models (MakeID, modelName) VALUES (56, ' Cayenne')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Cayenne SUV')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 911')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Panamera')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Cayman S')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 718 Boxter')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 918 Spyder')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Macan')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 997')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 914')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 912')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 924')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 928')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 930')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 944')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 356')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 959')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 968')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Panamera 4 sports sedan')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Macan SUV ')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Caymancoupe')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Carrera GT')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Boxster 2 roadster')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 911 Targa 4')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 911 GT1 Straﬂenversion')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 911 4coupe, targa and cabriolet')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Boxster')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 912')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Panamera Turbo')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Carrera')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Cayman')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 64')
INSERT INTO models (MakeID, modelName) VALUES (56, ' WSC-95 / LMP1-98')
INSERT INTO models (MakeID, modelName) VALUES (56, ' RS Spyder (9R6)')
INSERT INTO models (MakeID, modelName) VALUES (56, '-March 89P')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Le Mans 2014 Project')
INSERT INTO models (MakeID, modelName) VALUES (56, ' LMP2000 (never raced)')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 962')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 961')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 956')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 936')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 935')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 934')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 918 RSR')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 917')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 910')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 909 Bergspyder')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 908')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 907')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 906')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 904')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 804')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 787')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 718 Cayman')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 550 Spyder')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 360 Cisitalia')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 114')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Panamericana')
INSERT INTO models (MakeID, modelName) VALUES (56, ' C88')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Boxster concept')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 989')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 969')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 959 Prototype')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 942')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 916 (flat-6 914)')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 901 (911 prototype)')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 695 (911 prototype)')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 356/1')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Type 110')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Super (38 hp)')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Standard (25 hp)')
INSERT INTO models (MakeID, modelName) VALUES (56, ' R22')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Master (50 hp)')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Junior (14 hp)')
INSERT INTO models (MakeID, modelName) VALUES (56, ' AP Series')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 312')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 108F')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Roxster')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 356 Carrera')
INSERT INTO models (MakeID, modelName) VALUES (56, ' TechArt 997 Carrera')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 993')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 996')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 964')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 911 GT2')
INSERT INTO models (MakeID, modelName) VALUES (56, ' CTR2')
INSERT INTO models (MakeID, modelName) VALUES (56, ' Rt 12')
INSERT INTO models (MakeID, modelName) VALUES (56, ' TechArt 997 Turbo')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 911 Carrera')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 911 GT3')
INSERT INTO models (MakeID, modelName) VALUES (56, ' TechArt Magnum')
INSERT INTO models (MakeID, modelName) VALUES (56, ' 914-6 GT')
INSERT INTO models (MakeID, modelName) VALUES (56, ' TECHART GTsport')