INSERT INTO models (MakeID, modelName) VALUES (25, ' CR-V')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Avancier')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Pilot')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Crosstour')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Element')
INSERT INTO models (MakeID, modelName) VALUES (25, ' BR-V')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Odyssey')
INSERT INTO models (MakeID, modelName) VALUES (25, ' N-One')
INSERT INTO models (MakeID, modelName) VALUES (25, ' StepWGN')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Jazz')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Vamos')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Civic')
INSERT INTO models (MakeID, modelName) VALUES (25, ' City')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Ascot')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Accord')
INSERT INTO models (MakeID, modelName) VALUES (25, ' CR-Z')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Airwave')
INSERT INTO models (MakeID, modelName) VALUES (25, ' HR-V')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Mobilio')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Stream')
INSERT INTO models (MakeID, modelName) VALUES (25, ' NSX')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Capa')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Urban EV concept')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Project 2&4')
INSERT INTO models (MakeID, modelName) VALUES (25, ' FCX')
INSERT INTO models (MakeID, modelName) VALUES (25, ' EV-N')
INSERT INTO models (MakeID, modelName) VALUES (25, ' FCX')
INSERT INTO models (MakeID, modelName) VALUES (25, ' FC Sport')
INSERT INTO models (MakeID, modelName) VALUES (25, ' HS')
INSERT INTO models (MakeID, modelName) VALUES (25, ' OSM')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Urban SUV')
INSERT INTO models (MakeID, modelName) VALUES (25, ' SUT')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Step Bus')
INSERT INTO models (MakeID, modelName) VALUES (25, ' SSM')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Small Hybrid Sports')
INSERT INTO models (MakeID, modelName) VALUES (25, ' S360')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Remix')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Puyo')
INSERT INTO models (MakeID, modelName) VALUES (25, ' OSM')
INSERT INTO models (MakeID, modelName) VALUES (25, ' N800')
INSERT INTO models (MakeID, modelName) VALUES (25, ' MV-99')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Model X')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Kiwami')
INSERT INTO models (MakeID, modelName) VALUES (25, ' J-WJ')
INSERT INTO models (MakeID, modelName) VALUES (25, ' J-VX')
INSERT INTO models (MakeID, modelName) VALUES (25, ' J-MW')
INSERT INTO models (MakeID, modelName) VALUES (25, ' J-MJ')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Imas')
INSERT INTO models (MakeID, modelName) VALUES (25, ' HSC')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Gear')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Fuya-Jo')
INSERT INTO models (MakeID, modelName) VALUES (25, ' FCX')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Dualnote (of DN-X)')
INSERT INTO models (MakeID, modelName) VALUES (25, ' ASM')
INSERT INTO models (MakeID, modelName) VALUES (25, ' ZEST')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Ridgeline')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Legend')
INSERT INTO models (MakeID, modelName) VALUES (25, ' FCX Clarity')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Brio')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Acty')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Wow')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Fit Shuttle')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Inspire')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Freed')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Elysion')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Ballade')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Life')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Integra')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Passport')
INSERT INTO models (MakeID, modelName) VALUES (25, ' That’s')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Odyssey/Shuttle')
INSERT INTO models (MakeID, modelName) VALUES (25, ' MDX')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Insight')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Fit')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Civic Hybrid (2003-present)')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Civic GX')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Civic GTi')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Civic Type R')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Hobio (2003-present)')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Fit Aria (1981-present)')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Caren (1990)')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Brio Amaze')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Ballade')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Quintet')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Prelude')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Life Pick-Up')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Life StepVan')
INSERT INTO models (MakeID, modelName) VALUES (25, ' 1300')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Z')
INSERT INTO models (MakeID, modelName) VALUES (25, ' N600')
INSERT INTO models (MakeID, modelName) VALUES (25, ' N360/N400')
INSERT INTO models (MakeID, modelName) VALUES (25, ' S800')
INSERT INTO models (MakeID, modelName) VALUES (25, ' L800')
INSERT INTO models (MakeID, modelName) VALUES (25, ' SM600')
INSERT INTO models (MakeID, modelName) VALUES (25, ' L700')
INSERT INTO models (MakeID, modelName) VALUES (25, ' T500')
INSERT INTO models (MakeID, modelName) VALUES (25, ' S600')
INSERT INTO models (MakeID, modelName) VALUES (25, ' S500')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Life Dunk')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Mobilio Spike')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Quint')
INSERT INTO models (MakeID, modelName) VALUES (25, ' S600')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Domani')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Concerto')
INSERT INTO models (MakeID, modelName) VALUES (25, ' N360')
INSERT INTO models (MakeID, modelName) VALUES (25, ' L700')
INSERT INTO models (MakeID, modelName) VALUES (25, ' T360')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Prelude')
INSERT INTO models (MakeID, modelName) VALUES (25, ' S500')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Beat')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Crossroad')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Torneo')
INSERT INTO models (MakeID, modelName) VALUES (25, ' S800')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Stepwgn')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Today')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Logo')
INSERT INTO models (MakeID, modelName) VALUES (25, ' CR-X del Sol')
INSERT INTO models (MakeID, modelName) VALUES (25, ' 1300')
INSERT INTO models (MakeID, modelName) VALUES (25, ' S-MX')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Orthia')
INSERT INTO models (MakeID, modelName) VALUES (25, ' CR-X')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Z')
INSERT INTO models (MakeID, modelName) VALUES (25, ' S2000')
INSERT INTO models (MakeID, modelName) VALUES (25, ' EV Plus')
INSERT INTO models (MakeID, modelName) VALUES (25, ' Z600')