INSERT INTO models (MakeID, modelName) VALUES (22, ' California T')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 488 Spider')
INSERT INTO models (MakeID, modelName) VALUES (22, ' Enzo f12tdf')
INSERT INTO models (MakeID, modelName) VALUES (22, ' GTC4Lusso')
INSERT INTO models (MakeID, modelName) VALUES (22, ' Enzo')
INSERT INTO models (MakeID, modelName) VALUES (22, ' Testa Rossa')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 612 Scaglietti')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 550')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 250 GTO')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 312 P')
INSERT INTO models (MakeID, modelName) VALUES (22, ' Dino')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 750 Monza')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 575M Maranello')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 195 Inter')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 312 PB')
INSERT INTO models (MakeID, modelName) VALUES (22, ' California')
INSERT INTO models (MakeID, modelName) VALUES (22, ' F12 Berlinetta')
INSERT INTO models (MakeID, modelName) VALUES (22, ' FF')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 458 Italia')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 275 GTB, GTS, GTB/4, NART Spider')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 599 GTB Fiorano')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 250')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 456')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 500 Superfast')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 365 GT4 2+2/400/412')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 250 GT SWB Breadvan (2819GT)')
INSERT INTO models (MakeID, modelName) VALUES (22, ' F12berlinetta')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 365 GTB/4 and GTS/4 “Daytona”')
INSERT INTO models (MakeID, modelName) VALUES (22, ' F430')
INSERT INTO models (MakeID, modelName) VALUES (22, ' F40')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 288 GTO')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 308 GTB and GTS')
INSERT INTO models (MakeID, modelName) VALUES (22, ' F355')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 328 GTB & GTS')
INSERT INTO models (MakeID, modelName) VALUES (22, ' Testarossa, 512 TR and F512 M')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 330')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 125 S')
INSERT INTO models (MakeID, modelName) VALUES (22, ' F50')
INSERT INTO models (MakeID, modelName) VALUES (22, ' P4/5 by Pininfarina')
INSERT INTO models (MakeID, modelName) VALUES (22, ' Auto Avio Costruzioni 815')
INSERT INTO models (MakeID, modelName) VALUES (22, ' Berlinetta Boxer')
INSERT INTO models (MakeID, modelName) VALUES (22, ' Testa Rossa (TR)')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 348')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 166 Inter')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 166')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 365')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 250 TR 61 Spyder Fantuzzi')
INSERT INTO models (MakeID, modelName) VALUES (22, ' Monza')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 550 Barchetta')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 333 SP')
INSERT INTO models (MakeID, modelName) VALUES (22, ' Mondial')
INSERT INTO models (MakeID, modelName) VALUES (22, ' GTC4Lusso T')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 212 Export')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 159 S')
INSERT INTO models (MakeID, modelName) VALUES (22, ' F50 GT')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 195 S')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 430 Scuderia')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 212 Inter')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 340 MM')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 312PB')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 575M Superamerica')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 308/208 GT4')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 360')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 637')
INSERT INTO models (MakeID, modelName) VALUES (22, ' FX')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 512')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 550 Maranello')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 575 Gt')
INSERT INTO models (MakeID, modelName) VALUES (22, ' LaFerrari')
INSERT INTO models (MakeID, modelName) VALUES (22, ' FXX')
INSERT INTO models (MakeID, modelName) VALUES (22, ' Mythos Concept')
INSERT INTO models (MakeID, modelName) VALUES (22, ' F430 Challenge')
INSERT INTO models (MakeID, modelName) VALUES (22, ' GG50')
INSERT INTO models (MakeID, modelName) VALUES (22, ' Millechili')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 488 Gtb')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 312P')
INSERT INTO models (MakeID, modelName) VALUES (22, ' GT4')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 166 S')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 400')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 250 GT Drogo')
INSERT INTO models (MakeID, modelName) VALUES (22, ' TR')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 328')
INSERT INTO models (MakeID, modelName) VALUES (22, ' Daytona')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 275')
INSERT INTO models (MakeID, modelName) VALUES (22, ' 456 GT')