INSERT INTO models (MakeID, modelName) VALUES (63, ' 600')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Alhambra')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Ateca')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Toledo')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Leon')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Leon ST')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Mii')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Leon X-PERIENCE')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Tarraco')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Ibiza')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Arona')
INSERT INTO models (MakeID, modelName) VALUES (63, ' 1400')
INSERT INTO models (MakeID, modelName) VALUES (63, ' 850 Sport')
INSERT INTO models (MakeID, modelName) VALUES (63, ' 128')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Ronda')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Ibiza Mk1')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Toledo Mk1')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Córdoba SX')
INSERT INTO models (MakeID, modelName) VALUES (63, ' León Mk1 Cupra R')
INSERT INTO models (MakeID, modelName) VALUES (63, ' 1430')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Córdoba')
INSERT INTO models (MakeID, modelName) VALUES (63, ' León TDI')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Cupra GT')
INSERT INTO models (MakeID, modelName) VALUES (63, ' IBL Concept')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Fura')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Arosa')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Exeo')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Marbella')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Málaga')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Fórmula')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Tango')
INSERT INTO models (MakeID, modelName) VALUES (63, ' IBE v2')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Bocanegra')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Bolero')
INSERT INTO models (MakeID, modelName) VALUES (63, ' 133')
INSERT INTO models (MakeID, modelName) VALUES (63, ' 132')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Salsa')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Altea')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Tribu')
INSERT INTO models (MakeID, modelName) VALUES (63, ' 132 Madrid')
INSERT INTO models (MakeID, modelName) VALUES (63, ' 850 Spider vl blue TCE')
INSERT INTO models (MakeID, modelName) VALUES (63, ' 850')
INSERT INTO models (MakeID, modelName) VALUES (63, ' León Twin drive')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Altea XL/Freetrack')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Proto')
INSERT INTO models (MakeID, modelName) VALUES (63, ' León Mk1')
INSERT INTO models (MakeID, modelName) VALUES (63, ' 1500')
INSERT INTO models (MakeID, modelName) VALUES (63, ' Inca')
INSERT INTO models (MakeID, modelName) VALUES (63, ' 1200 Sport')