INSERT INTO models (MakeID, modelName) VALUES (43, ' F1')
INSERT INTO models (MakeID, modelName) VALUES (43, ' P1')
INSERT INTO models (MakeID, modelName) VALUES (43, ' 540C')
INSERT INTO models (MakeID, modelName) VALUES (43, ' 675LT')
INSERT INTO models (MakeID, modelName) VALUES (43, ' 570S')
INSERT INTO models (MakeID, modelName) VALUES (43, ' 650S')
INSERT INTO models (MakeID, modelName) VALUES (43, ' SLR ')
INSERT INTO models (MakeID, modelName) VALUES (43, ' MP4-12C')
INSERT INTO models (MakeID, modelName) VALUES (43, ' M2B')
INSERT INTO models (MakeID, modelName) VALUES (43, ' M1A')
INSERT INTO models (MakeID, modelName) VALUES (43, ' M8D')
INSERT INTO models (MakeID, modelName) VALUES (43, ' M16C')
INSERT INTO models (MakeID, modelName) VALUES (43, ' F1 GTR')
INSERT INTO models (MakeID, modelName) VALUES (43, ' M7A')
INSERT INTO models (MakeID, modelName) VALUES (43, ' MP4/98T')
INSERT INTO models (MakeID, modelName) VALUES (43, ' GT')
