INSERT INTO models (MakeID, modelName) VALUES (47, ' ASX Model')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Mirage')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Mirage G4')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Montero Sport')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Pajero')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Xpander')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Adventure')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Eclipse Cross')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Strada')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Outlander')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Lancer Evolution')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Galant')
INSERT INTO models (MakeID, modelName) VALUES (47, ' RVR')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Dion')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Toppo')
INSERT INTO models (MakeID, modelName) VALUES (47, ' 380')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Dingo')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Magna')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Endeavor')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Maven')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Grandis')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Colt')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Savrin')
INSERT INTO models (MakeID, modelName) VALUES (47, ' L300')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Starion')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Space Star')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Pajero Junior')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Pistachio')
INSERT INTO models (MakeID, modelName) VALUES (47, ' i')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Proudia')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Tredia')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Diamante')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Carisma')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Zinger')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Emeraude ')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Eterna Sava ')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Eterna Sigma ')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Eterna ')
INSERT INTO models (MakeID, modelName) VALUES (47, ' L200')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Galant Sigma ')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Aspire ')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Debonair ')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Galant Sports ')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Lancer Cedia ')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Dignity')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Lancer ')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Sigma')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Libero')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Delica ')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Cordia ')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Chariot ')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Challenger')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Eclipse ')
INSERT INTO models (MakeID, modelName) VALUES (47, ' eK ')
INSERT INTO models (MakeID, modelName) VALUES (47, ' FTO ')
INSERT INTO models (MakeID, modelName) VALUES (47, ' GTO ')
INSERT INTO models (MakeID, modelName) VALUES (47, ' i Miev')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Legnum')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Colt 1100')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Colt 1000')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Minicab')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Model A')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Eagle Talon')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Lancer 1600 GSR')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Colt 800')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Galant FTO')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Galant VR-4')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Colt 1500')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Lancer EX')
INSERT INTO models (MakeID, modelName) VALUES (47, ' PX33')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Freeca')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Town Box')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Truck')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Racing Lancer')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Eagle Vista')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Galant Lambda')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Fuso Aero Bus')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Pajero iO')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Galant GTO')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Eagle Summit')
INSERT INTO models (MakeID, modelName) VALUES (47, ' 500')
INSERT INTO models (MakeID, modelName) VALUES (47, ' Colt 600')
INSERT INTO models (MakeID, modelName) VALUES (47, ' XM')