INSERT INTO models (MakeID, modelName) VALUES (38, ' ES')
INSERT INTO models (MakeID, modelName) VALUES (38, ' GS')
INSERT INTO models (MakeID, modelName) VALUES (38, ' IS')
INSERT INTO models (MakeID, modelName) VALUES (38, ' GX')
INSERT INTO models (MakeID, modelName) VALUES (38, ' LX')
INSERT INTO models (MakeID, modelName) VALUES (38, ' LFA')
INSERT INTO models (MakeID, modelName) VALUES (38, ' RC')
INSERT INTO models (MakeID, modelName) VALUES (38, ' RX')
INSERT INTO models (MakeID, modelName) VALUES (38, ' RCF')
INSERT INTO models (MakeID, modelName) VALUES (38, ' LS')
INSERT INTO models (MakeID, modelName) VALUES (38, ' LC')
INSERT INTO models (MakeID, modelName) VALUES (38, ' NX')
INSERT INTO models (MakeID, modelName) VALUES (38, ' HS')
INSERT INTO models (MakeID, modelName) VALUES (38, ' CT Car Model')
INSERT INTO models (MakeID, modelName) VALUES (38, ' SC')
INSERT INTO models (MakeID, modelName) VALUES (38, ' LC500h')
