INSERT INTO models (MakeID, modelName) VALUES (31, ' XF')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XJ')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XE')
INSERT INTO models (MakeID, modelName) VALUES (31, ' F-TYPE')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XKR Cabriolet')
INSERT INTO models (MakeID, modelName) VALUES (31, ' F-Pace')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XK')
INSERT INTO models (MakeID, modelName) VALUES (31, ' E-Type')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XJ-S')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XFR')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XFR-S')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XKR-S')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XJR')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XJL')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XKR')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XJ220')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XK120')
INSERT INTO models (MakeID, modelName) VALUES (31, ' D-Type')
INSERT INTO models (MakeID, modelName) VALUES (31, ' C-Type')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XK140')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XK150')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XKSS')
INSERT INTO models (MakeID, modelName) VALUES (31, ' Sport XJR-15')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XJR-11')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XJR-9')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XJ13')
INSERT INTO models (MakeID, modelName) VALUES (31, ' X-Type')
INSERT INTO models (MakeID, modelName) VALUES (31, ' Daimler Sovereign')
INSERT INTO models (MakeID, modelName) VALUES (31, ' Mark X & 420G')
INSERT INTO models (MakeID, modelName) VALUES (31, ' S-Type')
INSERT INTO models (MakeID, modelName) VALUES (31, ' Mark 2, 240 and 340')
INSERT INTO models (MakeID, modelName) VALUES (31, ' Mark IX')
INSERT INTO models (MakeID, modelName) VALUES (31, ' Mark 1')
INSERT INTO models (MakeID, modelName) VALUES (31, ' Mark VII')
INSERT INTO models (MakeID, modelName) VALUES (31, ' Mark VII M')
INSERT INTO models (MakeID, modelName) VALUES (31, ' Mark VIII')
INSERT INTO models (MakeID, modelName) VALUES (31, ' SS')
INSERT INTO models (MakeID, modelName) VALUES (31, ' Mark V')
INSERT INTO models (MakeID, modelName) VALUES (31, ' 420 and Daimler Sovereign')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XJR-14')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XJR-15')
INSERT INTO models (MakeID, modelName) VALUES (31, ' Mark IV')
INSERT INTO models (MakeID, modelName) VALUES (31, ' Advanced Lightweight Coupe Concept')
INSERT INTO models (MakeID, modelName) VALUES (31, ' XJS')
