INSERT INTO models (MakeID, modelName) VALUES (37, ' Range Rover Evoque')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Range Rover Velar')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Discovery')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Range Rover Sport')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Defender')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Range Stormer')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Discovery Sport')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Range Rover ')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Range Rover')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Range Rover ')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Range Rover')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Freelander ')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Range Rover Classic ')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Range Rover ')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Discovery 4')
INSERT INTO models (MakeID, modelName) VALUES (37, ' DC100')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Series')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Wolf')
INSERT INTO models (MakeID, modelName) VALUES (37, ' 1/2 ton Lightweight')
INSERT INTO models (MakeID, modelName) VALUES (37, ' 101 Forward Control')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Series IIA')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Series II ')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Series III')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Rover CityRover')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Long Range Patrol Vehicle')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Llama ')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Perentie ')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Tangi ')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Ranger Special Operations Vehicle')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Snatch')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Shorland armoured car')
INSERT INTO models (MakeID, modelName) VALUES (37, ' TACR2')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Defender Ice Edition 2010')
INSERT INTO models (MakeID, modelName) VALUES (37, ' Sterling')