INSERT INTO models (MakeID, modelName) VALUES (21, ' Dart')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Durango')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Journey')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Grand Caravan')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Challenger')
INSERT INTO models (MakeID, modelName) VALUES (21, ' SRT Viper')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Charger')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Kingsway')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Avenger')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Caravan')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Coronet')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Phoenix')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Dakota')
INSERT INTO models (MakeID, modelName) VALUES (21, ' EV')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Stratus')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Mayfair')
INSERT INTO models (MakeID, modelName) VALUES (21, ' M37')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Polara')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Super Bee')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Grand Caravan 30th Anniversary')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Dart GTS')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Journey Blacktop')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Archives')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Dart GT')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Avenger Blacktop')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Grand Caravan Blacktop')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Charger Redline')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Journey Crossroad')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Coronet R/T')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Charger Blacktop')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Challenger 100th Anniversary Edition')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Viper SRT')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Raider')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Ram Pickup 2500')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Custom 880')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Viper SRT TA')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Challenger Shaker')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Dart Swinger')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Dart Demon')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Dart 413')
INSERT INTO models (MakeID, modelName) VALUES (21, ' SRT Viper GT3 R')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Challenger Blacktop')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Ram Daytona')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Charger 500')
INSERT INTO models (MakeID, modelName) VALUES (21, ' 50 Series')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Town Wagon')
INSERT INTO models (MakeID, modelName) VALUES (21, ' 440')
INSERT INTO models (MakeID, modelName) VALUES (21, ' 500')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Viscount')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Adventurer')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Viper E85')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Crusader')
INSERT INTO models (MakeID, modelName) VALUES (21, ' C Series')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Warlock')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Polara 500')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Neon SRT-4')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Diplomat')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Regent')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Meadowbrook')
INSERT INTO models (MakeID, modelName) VALUES (21, ' La Femme')
INSERT INTO models (MakeID, modelName) VALUES (21, ' 400')
INSERT INTO models (MakeID, modelName) VALUES (21, ' 330')
INSERT INTO models (MakeID, modelName) VALUES (21, ' 600')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Matador')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Rampage')
INSERT INTO models (MakeID, modelName) VALUES (21, ' B-Series')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Ram SRT-10')
INSERT INTO models (MakeID, modelName) VALUES (21, ' D Series')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Power Wagon')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Charger Daytona')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Ram Rumble Bee')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Colt')
INSERT INTO models (MakeID, modelName) VALUES (21, ' Hennessey Viper Venom 1000 Twin Turbo')
INSERT INTO models (MakeID, modelName) VALUES (21, ' B Series')