INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'X6' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'X3' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'X4' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '5 Series' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'X5' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '6 Series' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '7 Series' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Z4 Roadster' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'X2' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'I8' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'X1' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'i Hydrogen' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Concept 4' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'i Next' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'iX3' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'X7 Concept' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'i Vision Dynamics' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Z4 Concept' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '8er Concept' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'concept X2' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '3.0 CSL Hommage' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Vision Future Luxury concept' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'M4' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Gran Lusso' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'concept X4' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Concept Active Tourer' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Active Tourer Concept' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '4Series Coupe' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Zagato Roadster' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Z4 Zagato Coupe' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'i3 coupe' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'i8 Concept' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'i3 concept' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '328 Hommage' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Vision Connecte rive' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Concept 6 series Coupe' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '5 Series GT' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'M1 Hommage' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Gina' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Concept X1' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Concept X6' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Concept CS' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Mille Miglia' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Z4' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'C 31' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '750hL' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '750i E38' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Z22' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Z9' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'E1' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Nazca C2' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'M8' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Turbo' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '02 Series' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'New Class' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '531' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '326' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Z3' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'M6' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Z4' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '1 Series' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '501' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'E9' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '501' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'New Six' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Z1' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Z8' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '503' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '600' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '507' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '2 Series Coupe' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '2 Series Active Tourer' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '3 Series Sedan' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '3 Series Gran Turismo' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '4 Series Coupe' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '4 Series Gran Coupe' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '5 Series Gran Turismo' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'E24' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'M3' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'M5' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'X6M' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Concept X6 ActiveHybrid' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '760' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '750' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '745i E23' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'New Class' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '2002tii' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '700' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '315' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Isetta' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '335' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '/ EMW 340' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'M5 E28' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '333i E30' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '325is E30' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '530 MLE' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '550' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '320i' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '530' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '325' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '330' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '550i' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '745' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '645' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '535' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '650' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '545' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '2002' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '528' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '1600' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '135' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '2002ti' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '128' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'H2R' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'F07' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'X3 3.0i SAV' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '525' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'X5 4.4i SAV' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'X5 4.8is SAV' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'X5 3.0i SAV' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '3200 CS' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'EMW 327' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '8 Series (E31)' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'M1' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '328' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'E36/7 M Roadster' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'E36/8 M Coupe' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'F3' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Brilliance 6' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Hydrogen 7' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '321' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '320' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '3 Series Compact' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '3/20' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'V7' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '340' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Mini E' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'Compact' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , '327' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'M Roadster' );
INSERT INTO models (MakeID, modelName) VALUES ( 8 , 'M Coupe' );