INSERT INTO models (MakeID, modelName) VALUES (71, ' Cerbera')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Sagaris')
INSERT INTO models (MakeID, modelName) VALUES (71, 'Griffith 400')
INSERT INTO models (MakeID, modelName) VALUES (71, 'Trident Roadster')
INSERT INTO models (MakeID, modelName) VALUES (71, ' 280i')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Cerbera Speed 12')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Chimaera')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Grantura Mk2')
INSERT INTO models (MakeID, modelName) VALUES (71, ' No. 2')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Jomar')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Open Sports')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Grantura II')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Grantura IIa')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Grantura III')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Grantura III 1800')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Grantura 1800S')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Griffith 200')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Grantura IV 1800S')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Tuscan V8')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Tuscan V6')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Vixen S3')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Vixen 1300')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Vixen 2500')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Vixen S4')
INSERT INTO models (MakeID, modelName) VALUES (71, ' 1600M')
INSERT INTO models (MakeID, modelName) VALUES (71, ' 2500M')
INSERT INTO models (MakeID, modelName) VALUES (71, ' 3000M')
INSERT INTO models (MakeID, modelName) VALUES (71, ' 3000M Turbo')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Taimar')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Taimar Turbo')
INSERT INTO models (MakeID, modelName) VALUES (71, ' 3000S')
INSERT INTO models (MakeID, modelName) VALUES (71, ' 3000S Turbo')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Tasmin 200')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Tasmin 280i')
INSERT INTO models (MakeID, modelName) VALUES (71, ' 350i')
INSERT INTO models (MakeID, modelName) VALUES (71, ' 350SX')
INSERT INTO models (MakeID, modelName) VALUES (71, ' 400SX')
INSERT INTO models (MakeID, modelName) VALUES (71, ' 350SE')
INSERT INTO models (MakeID, modelName) VALUES (71, ' 390SE')
INSERT INTO models (MakeID, modelName) VALUES (71, ' 400SE')
INSERT INTO models (MakeID, modelName) VALUES (71, ' 420SE')
INSERT INTO models (MakeID, modelName) VALUES (71, ' 450SE')
INSERT INTO models (MakeID, modelName) VALUES (71, ' 420SEAC')
INSERT INTO models (MakeID, modelName) VALUES (71, ' 450SEAC')
INSERT INTO models (MakeID, modelName) VALUES (71, ' S')
INSERT INTO models (MakeID, modelName) VALUES (71, ' S2')
INSERT INTO models (MakeID, modelName) VALUES (71, ' S3(C)')
INSERT INTO models (MakeID, modelName) VALUES (71, ' S4C')
INSERT INTO models (MakeID, modelName) VALUES (71, ' V8S')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Griffith')
INSERT INTO models (MakeID, modelName) VALUES (71, ' T440R')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Tamora')
INSERT INTO models (MakeID, modelName) VALUES (71, ' T350')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Tuscan')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Typhon')
INSERT INTO models (MakeID, modelName) VALUES (71, ' T37')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Vixen')
INSERT INTO models (MakeID, modelName) VALUES (71, ' 450 SEAC')
INSERT INTO models (MakeID, modelName) VALUES (71, ' 420 SEAC')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Tasmin')
INSERT INTO models (MakeID, modelName) VALUES (71, ' S Series')
INSERT INTO models (MakeID, modelName) VALUES (71, ' M Series')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Grantura')
INSERT INTO models (MakeID, modelName) VALUES (71, ' Tuscan Speed 6')