INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'5-Passenger' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'8-50' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'8-90 Master' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'8-90' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Apollo' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Bengal' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Blackhawk' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Bug Race' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Cascada' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Centieme' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Centurion' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Century Series 60' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Century' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Coachbuilder' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Convertible' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'ENVISION' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Electra' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Empire Series 40' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Enclave' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Encore' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Estate Wagon' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Estate' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'GL8' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'GSX' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Gran Sport' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Hearse' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Holden Caprice' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Invicta' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'LaCrosse' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'LeSabre' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Limited' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Lucerne' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Marquette' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Master Series 60' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Master' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Model 17' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'NA 8/50' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'NA 8/60' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'NA 8/90' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Park Avenue Essence' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Park Avenue' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'REGAL TOURX' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Rainier' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Reatta' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Regal GS' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Regal' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Rendezvous' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Riviera GS' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Riviera Gran Sport' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Riviera' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Roadmaster Riviera' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Roadmaster' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Roadster' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Saturn Astra' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Series 40 DA' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Series 40 Special' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Skyhawk' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Skylark Gran Sport' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Skylark' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Somerset' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Special' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Sport Wagon' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Super' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Terraza' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Vanderbilt Cup' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Velite' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Verano' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Wildcat' );
INSERT INTO models (MakeID, modelName) VALUES ( 10 ,'Y-Job' );