INSERT INTO models (MakeID, modelName) VALUES (68, ' Model S')
INSERT INTO models (MakeID, modelName) VALUES (68, ' Model X')
INSERT INTO models (MakeID, modelName) VALUES (68, ' Cybertruck')
INSERT INTO models (MakeID, modelName) VALUES (68, ' Model 3')
INSERT INTO models (MakeID, modelName) VALUES (68, ' Model Y')
INSERT INTO models (MakeID, modelName) VALUES (68, ' Roadster Sport 2.5')