INSERT INTO models (MakeID, modelName) VALUES (64, ' Superb')
INSERT INTO models (MakeID, modelName) VALUES (64, ' 1100 GT')
INSERT INTO models (MakeID, modelName) VALUES (64, ' Vision X')
INSERT INTO models (MakeID, modelName) VALUES (64, ' Vision E')
INSERT INTO models (MakeID, modelName) VALUES (64, ' VisionC')
INSERT INTO models (MakeID, modelName) VALUES (64, ' Joyster')
INSERT INTO models (MakeID, modelName) VALUES (64, ' MissionL')
INSERT INTO models (MakeID, modelName) VALUES (64, ' Vision D')
INSERT INTO models (MakeID, modelName) VALUES (64, ' Octavia')
INSERT INTO models (MakeID, modelName) VALUES (64, ' 1101 “Tudor”')
INSERT INTO models (MakeID, modelName) VALUES (64, ' Fabia')
INSERT INTO models (MakeID, modelName) VALUES (64, ' Yeti')
INSERT INTO models (MakeID, modelName) VALUES (64, ' Rapid')
INSERT INTO models (MakeID, modelName) VALUES (64, ' Roomster')
INSERT INTO models (MakeID, modelName) VALUES (64, ' Mission')
