INSERT INTO models (MakeID, modelName) VALUES (51, ' Zonda Tricolore')
INSERT INTO models (MakeID, modelName) VALUES (51, ' Zonda R')
INSERT INTO models (MakeID, modelName) VALUES (51, ' Zonda Absolute')
INSERT INTO models (MakeID, modelName) VALUES (51, ' Zonda Cinque')
INSERT INTO models (MakeID, modelName) VALUES (51, ' Huayra')
INSERT INTO models (MakeID, modelName) VALUES (51, ' Zonda Cinque Roadster')
INSERT INTO models (MakeID, modelName) VALUES (51, ' Zonda C12')
INSERT INTO models (MakeID, modelName) VALUES (51, ' Zonda F')
INSERT INTO models (MakeID, modelName) VALUES (51, ' Zonda Revolucion')
INSERT INTO models (MakeID, modelName) VALUES (51, ' Zonda S 7.3')
INSERT INTO models (MakeID, modelName) VALUES (51, ' Zonda GJ')
INSERT INTO models (MakeID, modelName) VALUES (51, ' Zonda PS')
INSERT INTO models (MakeID, modelName) VALUES (51, ' Zonda Roadster')
INSERT INTO models (MakeID, modelName) VALUES (51, ' Zonda Roadster F')
INSERT INTO models (MakeID, modelName) VALUES (51, ' Zonda Uno')