INSERT INTO models (MakeID, modelName) VALUES (60, ' CTR2')
INSERT INTO models (MakeID, modelName) VALUES (60, ' CTR3')
INSERT INTO models (MakeID, modelName) VALUES (60, ' Dakara')
INSERT INTO models (MakeID, modelName) VALUES (60, ' SCR')
INSERT INTO models (MakeID, modelName) VALUES (60, ' BTR')
INSERT INTO models (MakeID, modelName) VALUES (60, ' RGT')
INSERT INTO models (MakeID, modelName) VALUES (60, ' 911')
INSERT INTO models (MakeID, modelName) VALUES (60, ' Model A Electric')
INSERT INTO models (MakeID, modelName) VALUES (60, ' RXL')
INSERT INTO models (MakeID, modelName) VALUES (60, ' Low')
INSERT INTO models (MakeID, modelName) VALUES (60, ' RK Coupe/Spyder')
INSERT INTO models (MakeID, modelName) VALUES (60, ' 3400S/3600S')
INSERT INTO models (MakeID, modelName) VALUES (60, ' R Turbo')
INSERT INTO models (MakeID, modelName) VALUES (60, ' R Kompressor')
INSERT INTO models (MakeID, modelName) VALUES (60, ' Turbo R')
INSERT INTO models (MakeID, modelName) VALUES (60, ' BTR2')
INSERT INTO models (MakeID, modelName) VALUES (60, ' RCT/RCT EVO')
INSERT INTO models (MakeID, modelName) VALUES (60, ' CTR “Yellowbird”')
INSERT INTO models (MakeID, modelName) VALUES (60, ' Turbo 3.3')
INSERT INTO models (MakeID, modelName) VALUES (60, ' 3800S')
INSERT INTO models (MakeID, modelName) VALUES (60, ' Rt35 S')
INSERT INTO models (MakeID, modelName) VALUES (60, ' Rt35')
INSERT INTO models (MakeID, modelName) VALUES (60, ' Rt 12')
INSERT INTO models (MakeID, modelName) VALUES (60, ' RGT-8')
INSERT INTO models (MakeID, modelName) VALUES (60, ' Turbo Florio')