INSERT INTO models (MakeID, modelName) VALUES (15, 'Ateca')
INSERT INTO models (MakeID, modelName) VALUES (15, 'Born')
INSERT INTO models (MakeID, modelName) VALUES (15, 'Formentor')
INSERT INTO models (MakeID, modelName) VALUES (15, 'Leon')
INSERT INTO models (MakeID, modelName) VALUES (15, 'Tavascan')