INSERT INTO models (MakeID, modelName) VALUES (53, ' Model 30U')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Acclaim')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Arrow')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Arrow Truck')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Barracuda')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Belvedere')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Breeze')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Business')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Caravelle')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Cambridge')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Champ')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Colt')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Colt Vista')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Commercial Car')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Concord')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Conquest')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Cranbrook')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Cricket')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Deluxe')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Duster')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Fury')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Gran Fury')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Grand Voyager')
INSERT INTO models (MakeID, modelName) VALUES (53, ' GTX')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Horizon')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Laser')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Model PA')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Model Q')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Model U')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Neon')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Plaza')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Prowler')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Roadking')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Road Runner')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Sapporo')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Satellite')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Savoy ')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Scamp ')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Six ')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Special Six')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Standard ')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Sundance')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Suburban')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Superbird ')
INSERT INTO models (MakeID, modelName) VALUES (53, ' TC3 ')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Trailduster')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Turismo ')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Valiant ')
INSERT INTO models (MakeID, modelName) VALUES (53, ' VIP ')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Volaré')
INSERT INTO models (MakeID, modelName) VALUES (53, ' Voyager ')